machinekit/machinekit

docs/src/drivers/hal_arm335xQEP.txt, src/hal/drivers/hal_arm335xQEP.c, src/hal/drivers/hal_arm335xQEP.h
Hi, I've fixed a bug in the index handling and have added counter-mode as well as a few other par maters.
Regards
Russell
=> BBB eqep driver

src/machinetalk/haltalk/haltalk_main.cc
=> machinetalk/haltalk: enabled zeroconf announcement on loopback device 

configs/sim/axis/axis.ini, src/emc/usr_intf/axis/extensions/emcmodule.cc
Patch to allow the setting of axis homing parameters while inside GUI.
=> emcmodule.cc: Added python method to set axis home parameters

src/hal/components/gantry_latching.comp
Adds a variant of the gantry HAL component that works "inverse" using latching. This enables additional home-offset fine tuning.
=> hal/components: added gantry-latching component

src/hal/drivers/mesa-hostmot2/bitfile.c, src/hal/drivers/mesa-hostmot2/bspi.c, src/hal/drivers/mesa-hostmot2/encoder.c, src/hal/drivers/mesa-hostmot2/hm2_7i43.c, src/hal/drivers/mesa-hostmot2/hm2_7i90.c, src/hal/drivers/mesa-hostmot2/hm2_pci.c, src/hal/drivers/mesa-hostmot2/hm2_test.c, src/hal/drivers/mesa-hostmot2/hm2_test.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/sserial.c, src/hal/drivers/mesa-hostmot2/sserial.h, src/hal/drivers/mesa-hostmot2/stepgen.c, src/hal/drivers/mesa-hostmot2/tram.c, src/hal/drivers/mesa-hostmot2/uart.c, src/hal/drivers/mesa-hostmot2/watchdog.c
Signed-off-by: Michael Geszkiewicz <micges@wp.pl>
=> hostmot2: update driver to current state from g.l.o.

src/emc/motion/motion.c, src/emc/motion/motion_debug.h, src/emc/tp/tp.c
Exports joint home and home_offset positions via HAL
Resolves machinekit/machinekit#423
=> Home offset

man/man1/axis-remote.1
Add --run / -R switches for remote running of current file to man page
=> Update axis-remote switches

src/Makefile, src/hal/drivers/mesa-hostmot2/hm2_eth.c, src/hal/drivers/mesa-hostmot2/hm2_eth.h, src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/lbp16.h, src/hal/drivers/mesa-hostmot2/tram.c
Signed-off-by: Michael Geszkiewicz <micges@wp.pl>
=> hostmot2: add support for mesanet ethernet boards 7i80, 7i76e, 7i92

src/machinetalk/mkwrapper/mkwrapper.py
and printing errors to stderr
This may fix a possible race condition when a error is reported during status update.
=> machinetalk/mkwrapper: created seperate tx container for error channel

src/configure.in
Fix for https://github.com/machinekit/machinekit/issues/432
=> configure: added nested variable replacement for machinkitcfg.py

configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper.hal, configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper.ini, configs/ARM/BeagleBone/BeBoPr++/Pepper/lineardelta.hal, configs/ARM/BeagleBone/BeBoPr++/Pepper/lineardelta.ini
=> Fix BeBoPr++ config files with paths that got broken.

src/machinetalk/mkwrapper/mkwrapper.py
This adds support for program extensions other than ngc to mkwrapper
=> machinetalk/mwkrapper: implemented program extensions

src/hal/components/div2.comp
adds the div2 component to simply HAL configuration where a quotient is needed
=> hal/components: added div2 component

src/hal/components/neg.comp
Adds a component that changes the sign of a floating point value.
=> hal/components: added neg component

configs/sim/axis/gladevcp/gladevcp_tab.ini, configs/sim/axis/sim_rostock.hal, src/emc/kinematics/lineardeltakins-common.h, src/emc/kinematics/lineardeltakins.c, src/emc/kinematics/lineardeltakins.cc
There are changes in the gladevcp_tab.ini file that should not be used. Don't know what I should do  without screwing up and adding yet another commit.  Suggestions?
=> Added joint offset hal pins to lineardeltakins

src/emc/tp/tp.c
I made a subtle mistake in the code that chooses whether to use trapezoidal or ramped acceleration, which can lead to strange behavior when using spindle-synced motion. The result was that short segments would sometimes be ramped up over a very long time (~20 seconds). This fix corrects the final velocity estimation so that this doesn't happen.
=> Ramped acceleration fix

src/hal/components/stats.comp
Uses a single-pass online algorithm. See also:
http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm
=> HAL components/stats: component to compute mean and variance of a signal

src/hal/lib/hal_lib.c, src/hal/lib/hal_priv.h, src/hal/lib/halpb.cc, tests/alias.0/expected, tests/loadrt.1/expected
this carries over two extensions from git.linuxcnc.org which I found useful
=> Hal lib fix

src/emc/tp/tp.c
The problem: Optimization falters when the queue only has a few segments
in it. Specifically, we can't be sure of the total segment length until
there is another segment after it (due to blending). The approach in the
past was very conservative, and basically aborted optimization entirely
if the queue had less than 3 segments in it.
This commit addresses this problem somewhat with 2 major changes:
1) Allow blending on segments already in progress, provided that a few
conditions are true (not doing parabolic blending already, less than
1/2 of the segment is complete).
2) Since a segment will never have more than 1/2 of it's length consumed
in a blend, the worst-case final velocity of the previous segment is the
maximum velocity that we can reach and still stop at the halfway point.
With …
=> tp: Improved handling of low-queue state

lib/python/machinekit/launcher.py
- added ini file specification to HAL file loading
- added function that runs and checks a command
=> lib/python/machinekit/launcher: updated functionality

src/Makefile, src/machinetalk/videoserver/Submakefile, src/machinetalk/videoserver/video.ini, src/machinetalk/videoserver/videoserver.py
This patch adds a videoserver Machinetalk application to provides a video service to stream webcam video using mjpeg streamer. For it to work a modified version of mjpeg_streamer with zmqserver plugin is necessary. This version can be found here: https://github.com/strahlex/mjpeg-streamer
=> machinetalk: added a videoserver component

nc_files/remap-subroutines/fdm/g28.ngc, nc_files/remap-subroutines/fdm/m600.ngc
Updated two FDM remaps codes:
- fixed syntax error in g28 code
- added m600 code
=> Fdm remap update

src/hal/lib/hal_pin.c
This was introduced in 51a0afc76, and while not fatal, this line
*(hal_data_u *)dummy_addr = *sig_data_addr;
potentially restores more bytes from the signal than intended (eg on a bit pin
it will still store sizeof(double) bytes) which may cause dummysig to
hold confusing values when inspected with a debugger
I would appreciate a long stare of a second pair of eyeballs
=> hal/unlink_pin: assure pin value on unlink is reset properly

src/rtapi/rtapi_msgd.cc, src/rtapi/rtapi_support.c
Rob and Alex reported lost log messages when turning on tp debugging, which creates absurd amounts of log entries.
This PR takes care of the issue.
The better solution longer term for debugging the tp would be to investigate these things in userland, for instance by a test harness around the  posix-flavor shared object using dlopen/dlsym like rtapi_app does.
=> Fix for lost log messages

src/emc/motion/command.c, src/emc/motion/mot_priv.h, src/emc/motion/motion.h, src/emc/nml_intf/emc.hh, src/emc/task/emctaskmain.cc, src/emc/task/taskintf.cc, src/emc/tp/tp.c, src/emc/tp/tp.h, src/emc/tp/tp_private.h, src/emc/tp/tp_shared.h
fixes the RT delay on thread <x> bug: https://github.com/machinekit/machinekit/issues/412
=> RT delay bug fix

src/hal/drivers/hal_zed_gpio.c
fix for https://github.com/machinekit/machinekit/issues/566
=> hal/drivers/zed_gpio: including stdio

src/hal/cython/machinekit/rtapi.pyx
- added automatic loadrt to newinst
- using UUID from environment in RTAPIcommand when uuid is not specified
=> RTAPI Cython API features

configs/ARM/BeagleBone/BeBoPr++/Pololu/BeBoPr++.hal, configs/ARM/BeagleBone/BeBoPr++/Pololu/TAKE-5.hal, configs/ARM/BeagleBone/BeBoPr++/Pololu/TAKE-5.ini
New configuration for TAKE-5 stepper board controlling 5 axes.
Also fixed some comments referring to wrong pin names (probably pre-bridge info).
=> Added configuration for 5-axes / TAKE-5.

configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper-DecaMux.hal, configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper-DecaMux.ini, configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper.hal, src/hal/components/pepper.c, src/hal/drivers/hal_pru_generic/Submakefile, src/hal/drivers/hal_pru_generic/pru_decamux.p, src/hal/drivers/hal_pru_generic/pru_generic.p, src/hal/drivers/hal_pru_generic/pru_wait.p
This PR needs code review and a build test, but should combine both Bas' original changes, the updates made by gjsmo along with some tweaks by me to setup for building two PRU binary files.
Intended to supersede PR # 578, if all looks good.
=> Add Decamux Support

src/hal/cython/machinekit/rtapi.pyx
update to https://github.com/machinekit/machinekit/pull/575 for package installs
=> python/machinekit/rtapi: improving RTAPIcommand for package installs

src/hal/cython/machinekit/hal.pyx, src/hal/cython/machinekit/hal_loadusr.pyx, src/hal/cython/machinekit/hal_net.pyx, src/hal/cython/machinekit/hal_signal.pyx
- implements operator style netting: https://github.com/machinekit/machinekit/issues/581
- implements loadusr
- adds possibilty to use net with objects
=> HAL Cython API features

src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/proto/proto/config.proto
Update to protobuf definitions and mklauncher
=> Machinetalk: Update for mklauncher

scripts/check-system-configuration.sh
Add '$ sudo udevadm trigger' to hint message.
=> scripts/check-system-configuration.sh: tidy hint message.

src/machinetalk/videoserver/videoserver.py
fixes the announcement problems lately discussed on the mailing list
=> machinetalk/videoserver: updated to use hostname.local announcements

src/hal/drivers/hal_bb_gpio.c, src/hal/drivers/hal_pru_generic/encoder.c, src/hal/drivers/hal_pru_generic/hal_pru_generic.c, src/hal/drivers/hal_pru_generic/hal_pru_generic.h, src/hal/drivers/hal_pru_generic/pwmgen.c, src/hal/drivers/hal_pru_generic/stepgen.c
fixup for https://github.com/machinekit/machinekit/issues/610
=> bb_gpio and hpg: changing HAL params to pins

share/axis/tcl/axis.tcl
see https://sourceforge.net/p/emc/mailman/emc-developers/thread/54A9DA86.9010505@highlab.com/
=> axis.tcl: workaround for tcl8.6 breakage

src/hal/components/delayline.c, src/rtapi/rtai-kernel.c, src/rtapi/rtai-kernel.h
Fix a couple of compiler warnings that were distracting during development
=> Minor warnings

configs/ARM/BeagleBone/BeBoPr-Bridge/velocity-extruding/lineardelta-vel-extr.hal, configs/ARM/BeagleBone/Probotix/Comet.hal
Update sample configs to use instantiated components
Updates for gantry and lincurve
=> Instantiated components clean up

src/hal/cython/machinekit/hal.pyx, src/hal/cython/machinekit/hal_component.pyx, src/hal/cython/machinekit/hal_rcomp.pyx
adds a interface for HAL remote components to the Python API
=> python/machinekit/hal: added RemoteComponent

src/Submakefile.skel
this answers the age-old question:
how do I compile a specific file or directory with specific compiler and linker flags for RT and userland?
=> note on custom build flags for RT and userland objects

nc_files/remap-subroutines/fdm/m207.ngc, nc_files/remap-subroutines/fdm/m221.ngc, nc_files/remap-subroutines/fdm/m701.ngc, nc_files/remap-subroutines/fdm/m702.ngc, nc_files/remap-subroutines/fdm/m710.ngc, nc_files/remap-subroutines/fdm/remap.ini
added new FDM remap subroutines
=> remap-subroutines/fdm: added M207, M221, M701, M702 and M710

src/hal/drivers/hal_arm335xQEP.c, src/hal/drivers/hal_arm335xQEP.h
Fix for https://github.com/machinekit/machinekit/issues/686
Tested with a servo-motor that runs with about 8ticks/period on full speed. This patch gives a far better resolution when running on low speeds.
Is there a place where this driver module is documented so I can update the documentation?
=> DO NOT MERGE: hal/drivers/hal_arm335xQEP: implementing period counter

configs/sim/axis/remap/list-recorder/README, configs/sim/axis/remap/list-recorder/axis_manualtoolchange.hal, configs/sim/axis/remap/list-recorder/core_sim9.hal, configs/sim/axis/remap/list-recorder/list-recorder.ini, configs/sim/axis/remap/list-recorder/locking_indexer.hal, configs/sim/axis/remap/list-recorder/nc_files/list.ngc, configs/sim/axis/remap/list-recorder/python/recorder.py, configs/sim/axis/remap/list-recorder/python/remap.py, configs/sim/axis/remap/list-recorder/python/toplevel.py, configs/sim/axis/remap/list-recorder/sim_spindle_encoder.hal, configs/sim/axis/remap/list-recorder/simulated_home.hal, configs/sim/axis/remap/list-recorder/tool.tbl, src/rtapi/rtai-kernel.c
remap/examples: record a list of gcodes, and replay
see thread: https://sourceforge.net/p/emc/mailman/emc-developers/thread/BLU0-SMTP1386266066EB037D5CD77F7B04E0@phx.gbl/
=> remap/examples: record a list of gcodes, and replay

lib/python/machinekit/service.py
Overseen line in https://github.com/machinekit/machinekit/pull/707
=> machinetalk/service: fixed oversight from previous commit

src/hal/i_components/wcompn.icomp
Useful e.g. for multi operating point PID loops
=> hal/i_component: added wcompn component

src/machinetalk/mkwrapper/mkwrapper.py, src/machinetalk/proto/proto/status.proto
Adding new features to mkwrapper:
- max-velocity and max-acceleration per axis
- total line number of loaded file
Cleaned up the protobuf message update code to make better use of Python features and improve maintainability.
=> mkwrapper updates

src/machinetalk/mkwrapper/mkwrapper.py, src/machinetalk/proto/proto/status.proto, src/machinetalk/proto/proto/types.proto
- merging upstream machinetalk-protobuf changes
- adds shutdown command  to mkwrapper
=> mkwrapper: implemented shutdown command

src/hal/drivers/hal_pru_generic/pwmgen.c, src/machinetalk/mkwrapper/mkwrapper.py
- Merged upstream machinetalk-protobuf with user commands field
- Implemented user command in mkwrapper
=> Mkwrapper: implemented user commands

src/machinetalk/mkwrapper/mkwrapper.py
implemented per axis increments to improve usability of the UIs
=> mkwrapper: implemented per axis increments

scripts/latency-test
Change Linuxcnc to Machinekit in dialog text
=> Some re-branding to machinekit whilst I am at it

src/Makefile
=> build: make RT objects depend on their .d (depends) file

src/hal/user_comps/xhc-hb04.cc
=> Fix incorrect left\rigth jogging

src/emc/usr_intf/stepconf/build_HAL.py, src/emc/usr_intf/stepconf/build_INI.py, src/emc/usr_intf/stepconf/pages.py, src/emc/usr_intf/stepconf/stepconf.py
rebranded stepconf & added leadshine stepper driver to pick list
this now gives machinekit configs it's own directorys .
=> re-brand stepconf

src/machinetalk/mkwrapper/mkwrapper.py
improves the parameters passed to the preview interpreter
=> machinetalk/mkwrapper: improved preview parameters handling

src/machinetalk/mkwrapper/mkwrapper.py
Fixes some potential thread synchronization issues related to error handling from different threads. Furthermore makes sure locks are used when accessing outgoing messages.
=> machinetalk/mkwrapper: improved thread synchronization and error handling

src/machinetalk/proto/README.md, src/machinetalk/proto/proto/types.proto, src/machinetalk/proto/scripts/protoc-gen-depends
update to machinetalk-protobuf master
=> Machinetalk proto update

src/machinetalk/mkwrapper/mkwrapper.py
Added support for command feedback to mkwrapper. When clients send a ticket with the protobuf message mkwrapper will respond with the corresponding command status.
=> mkwrapper: implemented command feedback

src/hal/utils/instcomp.g
Changed to explain instantiable component loading via newinst
and show alternative pin naming if newinst used
=> Revamp of instcomp man page generation

.travis.yml
Send email only on failures.
[ci skip]
=> Disable Travis email notifications 

.travis/build_rip_helper.sh
Runtests complains about missing directories
=> Fixed missing mk user home directory

.travis.yml, .travis/build_deb.sh
Source deb is also built for amd64
=> Added support for armhf builds

.travis/get_sftp_key.sh
This fixes the failure in build [#50.2](https://travis-ci.org/machinekit/machinekit/jobs/95304076)
=> Create temporary files out of the build tree

src/rtapi/rtapi_compat.h
as reported by Gemi in https://github.com/machinekit/machinekit/issues/834#issuecomment-165452528
=> rtapi: fix for #834

src/machinetalk/config-service/configserver.py
configserver did not support pings. This PR adds this feature.
=> configserver: implemented ping

src/machinetalk/mkwrapper/mkwrapper.py
* Resolved issue #847 "mkwrapper generates SIGABRT randomly on Raspberry Pi2"
* use single thread to synchronize send() and recv() of the zmq socket
* merge LinuxCNCWrapper.poll() to LinuxCNCWrapper.process_sockets()
* prevent process_sockets() from polling earlier than pollInterval
=> mkwrapper.py: use single thread to synchronize zmq send and recv

src/machinetalk/config-service/configserver.py, src/machinetalk/haltalk/haltalk.hh, src/machinetalk/haltalk/haltalk_command.cc, src/machinetalk/haltalk/haltalk_introspect.cc, src/machinetalk/include/pbutil.hh, src/machinetalk/lib/pbutil.cc, src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/mkwrapper/mkwrapper.py
Fix for https://github.com/machinekit/machinekit/issues/859
and https://github.com/machinekit/machinekit/issues/860
Please test.
=> Machinetalk hardening

.travis.yml, .travis/docker_run.sh
=> changed docker build container

.travis.yml
This reverts commit bb81b55178f665e3ef9b8679377d4b76579e4b11, reversing
changes made to 14be0bffff068eb65281b60b3f2a5ff31e9e88ae.
=> Revert "Merge pull request #883 from kinsamanka/updates"

.travis.yml, .travis/get_sftp_key.sh, .travis/send_binaries.sh, .travis/send_status.sh
Reverts machinekit/machinekit#887
=> Revert "switching to new sftp server"

.travis.yml, .travis/check_sftp.sh, .travis/send_binaries.sh, .travis/send_status.sh
=> DO NOT MERGE: removed legacy sftp code

.travis.yml, .travis/build_deb.sh, .travis/build_rip.sh, .travis/build_rip_helper.sh, .travis/docker_run.sh
=> removed ccache

man/man3/hm2_pktuart_read.3hm2, man/man3/hm2_pktuart_send.3hm2, man/man3/hm2_pktuart_setup.3hm2, src/Makefile, src/hal/components/mesa_pktgyro_test.comp, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/pins.c, src/hal/drivers/mesa-hostmot2/pktuart.c
Signed-off-by: sirop           email: boris.skegin.de at gmail.com
=> PktUART driver for MESA

src/hal/drivers/mesa-hostmot2/hm2_test.c
=> hm2_test.c: exit HAL component on failure

src/hal/drivers/hal_pru_generic/encoder.c, src/hal/drivers/hal_pru_generic/hal_pru_generic.c, src/hal/drivers/hal_pru_generic/hal_pru_generic.h
Validated from 5 Hz to 100 kHz
Maximum measurement error is 1%
=> Add support for velocity estimation in hal_pru_generic encoder

src/hal/drivers/hal_pru_generic/encoder.c
Switch bool to hal_bool to fix a build error that got by the PR checks
=> hal_pru_generic: Fix errant bool type

scripts/hm2soc_program_fpga, src/hal/drivers/mesa-hostmot2/hm2_7i43.c, src/hal/drivers/mesa-hostmot2/hm2_pci.c, src/hal/drivers/mesa-hostmot2/hm2_soc.c, src/hal/drivers/mesa-hostmot2/hm2_soc.h, src/hal/drivers/mesa-hostmot2/hm2_test.c, src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/rtapi/rtapi_compat.c, src/rtapi/rtapi_compat.h
see https://github.com/machinekit/machinekit/issues/865#issuecomment-209530838
=> polish the hm2_soc driver

src/hal/components/Submakefile, src/hal/user_comps/Submakefile, src/hal/user_comps/adxl345.comp, src/hal/user_comps/hal_gy86.py, src/hal/utils/comp.g, tests/usercomp.0/rand.comp
the sensor HAL comps might be useful for demos
=> demonstrate comp-generated HAL usercomps, and add a few useful ones

src/Makefile, src/emc/kinematics/XYZACkins.c
dont merge yet, let's see how this fares
=> Xyza ckins

.jenkins/build-manpages.sh
CI support - no impact on packaging, can be merged right away
=> .jenkins/build-manpages.sh: script for machinekit-manpages job

configs/hm2-soc-stepper/5i25-socfpga.ini, configs/hm2-soc-stepper/5i25-zynq.ini
better out-of-the-box experience
=> 5i25-soc: split into zynq, socfpga config

configs/hm2-soc-stepper/irqtest.hal, src/hal/drivers/mesa-hostmot2/hm2_soc.c, src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c, src/hal/drivers/mesa-hostmot2/hm2_soc_ol.h, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/lib/hal_funct.c, src/hal/lib/hal_thread.c, src/hal/utils/halcmd.c, src/hal/utils/halcmd_commands.c, src/hal/utils/halcmd_commands.h, src/rtapi/rtapi_app.cc, src/rtapi/rtapi_compat.c, src/rtapi/rtapi_compat.h, src/rtapi/rtapi_task.c
a first step towards addressing #687
=> add wait-for-IRQ function to hm2_soc_ol

.jenkins/build-manpages.sh, src/Makefile, src/hal/components/Submakefile, src/hal/i_components/Submakefile, src/hal/utils/comp.g, src/hal/utils/instcomp.g
this should enable switching the man repository to mk/mk
lets make sure this builds
=> frontmatter insertion into generated component asciidoc

README.asciidoc
Remove duplicated information and now dead links and replace with one link to the new site
=> Change README.asciidoc re update in website

scripts/halrun.in, src/hal/lib/hal_lib.c, src/hal/utils/halcmd_commands.c, src/rtapi/rt-preempt.c, src/rtapi/rtapi_app.cc
initial fix for https://github.com/machinekit/mksocfpga/issues/45#issuecomment-225351844 
(NB: the fix is NOT for the problem mentioned in the issue's name)
=> Rtapi support blocking threadfuncts

src/Makefile, src/hal/icomp-example/icomp.c, src/hal/icomp-example/lutn-demo.c, src/hal/icomp-example/lutn-demo.hal, src/hal/icomp-example/lutn-demo.py, src/hal/lib/hal.h, src/hal/lib/hal_comp.c, src/hal/utils/instcomp.g, src/machinetalk/msgcomponents/pbring.c, src/rtapi/rtapi_app.cc
this was a tad underdesigned. 
@ArcEye - this now is as discussed
=> fix the HAL instantiation API

man/man9/hal_pru_generic.9.asciidoc
Initial version of the hal_pru_generic man page.
=> hal_pru_generic.9 Initial version

src/machinetalk/config-service/configserver.py, src/machinetalk/mkwrapper/emcstatusclient.py, src/machinetalk/msgcomponents/pbring-demo.py
missed with last PR, please merge
=> machinetalk-protobuf: update imports

src/machinetalk/mkwrapper/mkwrapper.py
for tool table update function
=> mkwrapper: fixed wrong parameter checks

src/machinetalk/mkwrapper/mkwrapper.py, src/machinetalk/proto/src/machinetalk/protobuf/status.proto
* fix INCH naming
* improved tool table handling
=> mkwrapper update

debian/control.in, scripts/hal-graph, src/Makefile, src/configure.ac
This PR adds the hal-graph tool. Very useful but adds additional dependencies. I am not sure how to proceed with such tools.
=> DO NOT MERGE: scripts: add hal-graph tool

src/machinetalk/proto/src/machinetalk/protobuf/firmware.proto
=> Firmware proto

src/machinetalk/Submakefile
Fix for https://github.com/machinekit/machinekit/issues/998
=> machinetalk-protobuf: fix dependency build

debian/machinekit.install, debian/rules.in, src/Makefile
Please check before merging!
Possibly fix for https://github.com/machinekit/machinekit/issues/999
How can I build the deb package locally?
=> machinetalk-protobuf: fix package install

.gitignore, configs/hm2-soc-stepper/5i25-socfpga.ini, configs/hm2-soc-stepper/custom-fwid.py, configs/hm2-soc-stepper/hm2-soc-ol-stepper-5i25.hal, configs/hm2-soc-stepper/irqtest.hal, src/Makefile, src/hal/drivers/mesa-hostmot2/fwid.c, src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c, src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h
a first cut - @cdsteinkuehler @the-snowwhite @ dkhughes - please have a look & maybe a spin
please do not merge yet - this should be tried with other hm2 configs to make sure this doesnt break existing configs
=> FirmwareID handling for socfpga firmware

src/machinetalk/proto/src/machinetalk/protobuf/status.proto
FIx for wrong protobuf tool data types
=> Tool types fix

.jenkins/build-manpages.sh
Required to get make-manpages stage of website-production working again
=> Amend build_manpages.sh - new paths & make targets

man/README, src/Makefile
=> Add man/README to direct users to new locations for manual pages

src/hal/drivers/mesa-hostmot2/encoder.c, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/pins.c
see also: https://github.com/machinekit/mksocfpga/issues/54 and
https://github.com/machinekit/machinekit-docs/pull/212
=> hm2:  support muxed and unmuxed encoders in a single config

src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/stepgen.c, src/hal/drivers/mesa-hostmot2/tp_pwmgen.c, src/hal/utils/halcmd_commands.c
@luminize - please review and give it a solid test - works for me
no wonder you tripped up over the table[] thing
=> hm2/stepgen: mutate params into pins

src/machinetalk/mklauncher/mklauncher.py
Adds the ability to shutdown the system via dbus to mklauncher. Can be useful to shutdown remote sessions without physical interface.
=> mklauncher: added shutdown via dbus

src/hal/utils/halcmd_commands.c
halcmd built-in help now includes documentation for the "newthread" command
=> update halcmd built-in help: add newthread

src/emc/rs274ngc/previewmodule.cc, src/machinetalk/proto/src/machinetalk/protobuf/preview.proto
* don't convert to inch
* send `PV_PREVIEW_START` and `PV_PREVIEW_END` messages
=> update for previewmodule.cc

src/Makefile, src/hal/drivers/mesa-hostmot2/dpll.c, src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c, src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/irq.c
This is a slightly more refactored version of external IRQ support using the dpll in a hostmot2 instance.
=> Updated DPLL IRQ support

configs/hm2-soc-stepper/irqtest.hal, src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c
part of "bringing zynq and cv in line" ;)
=> hm2_soc_ol.c touchups

share/axis/tcl/axis.tcl
Add axis designations to axis_activated command for joints as well as axes
Fixes issue #1048
=> Fix commit #1042

src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/proto/src/machinetalk/protobuf/config.proto
Adds support for sorting the launcher entries based on the priority parameter.
=> mklauncher: adding support for sorting

src/emc/rs274ngc/previewmodule.cc, src/rtapi/rtapi_app.cc
compiler complains when a printf string is not a string literal
=> fix string literal warnings

configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/.gitignore, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/CRAMPS.bbio, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/README.md, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/cramps.py, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/cramps2_cape.bbio, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/fabrikator-mini.ini, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/fabrikator_mini.py, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/launcher.ini, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/run.py, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/storage.ini, configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/tool.tbl, configs/ARM/BeagleBone/MendelMax-CRAMPS/.gitignore, configs/ARM/BeagleBone/MendelMax-CRAMPS/CRAMPS.bbio, configs/ARM/BeagleBone/MendelMax-CRAMPS/CRAMPS.ini, configs/ARM/BeagleBone/MendelMax-CRAMPS/README.md, configs/ARM/BeagleBone/MendelMax-CRAMPS/cramps.py, configs/ARM/BeagleBone/MendelMax-CRAMPS/cramps2_cape.bbio, configs/ARM/BeagleBone/MendelMax-CRAMPS/launcher.ini, configs/ARM/BeagleBone/MendelMax-CRAMPS/mendelmax.py, configs/ARM/BeagleBone/MendelMax-CRAMPS/run.py, configs/ARM/BeagleBone/MendelMax-CRAMPS/storage.ini, configs/ARM/BeagleBone/MendelMax-CRAMPS/tool.tbl, lib/python/fdm/config/base.py, lib/python/fdm/config/motion.py, lib/python/fdm/config/rcomps.py, lib/python/fdm/config/storage.py, lib/python/fdm/config/velocity_extrusion.py
Adds the Python `fdm.config` library and sample configurations.
=> adding FDM library and configs

src/machinetalk/mkwrapper/mkwrapper.py
causes bad comments to cause harm
=> mkwrapper: fix problem with greedyness in tool table

src/emc/rs274ngc/previewmodule.cc, src/machinetalk/mkwrapper/mkwrapper.py
Preview now uses the current tool table and other data from `linuxcnc.stat`. Furthermore, problems caused by multiple preview requests are now prevented by clearing the input argument queue.
=> mkwrapper: preview fixes

configs/by_machine/compact5/Compact5.hal, configs/by_machine/compact5/Compact5.ini, configs/by_machine/compact5/README, configs/by_machine/compact5/toolchanger.comp
Config from user Mike Ross <rossmichael1974@gmail.com>
with toolchanger component based upon one from my examples
in docs.
=> Add new machine config for Emco Compact5 using BBB and cape

src/hal/user_comps/hal_pwm_pca9685.py
Adds reset functionality to the driver for the PCA9685 PWM IC. The reset pin can be connect to estop-reset in order to ensure correct initialization after a power-down.
=> hal_pwm_pca9685: implementing reset pin

src/hal/i_components/lincurve.icomp, src/hal/i_components/lincurvev2.icomp
Previously fixed in #783 but reverted by old code in multicore merge
Fixes #1127
=> Fix lincurve and lincurvev2 bracketing auto-completion typo error

src/hal/lib/hal.h
Fix for https://github.com/machinekit/machinekit/issues/1137
=> hal.h: fix wrong type definitions

lib/python/fdm/config/base.py
=> Amend python function to use instantiated version of watchdog

src/Makefile, src/Makefile.inc.in, src/configure.ac
=> Changes to make webtalk build and libwebsockets dependency optional

src/hal/drivers/Submakefile, src/hal/drivers/hal_p260c.c
=> Add HAL driver to talk to P260C I/O boards on an RS-485 chain.

lib/python/machinekit/launcher.py
Remove this check since webtalk is now optional
https://github.com/machinekit/machinekit/issues/1129
=> machinekit/launcher: don't check for webtalk

src/machinetalk/include/halpb.hh
fixes problem described in https://github.com/machinekit/machinekit/issues/1123
=> haltalk: fix typo

src/hal/i_components/conv.icomp.in
=> Fix non zero return paths from function in generated conv components

src/hal/utils/halcmd_commands.c
Inadvertently removed during multicore merge
This workaround is a temporary measure to keep the xhc-hb04 pendant working.
xhc-hb04.tcl uses command line halcmd outputs against tests which are fixed
in expectation of a particular return. (ie from linuxcnc circa 2014)
Changes to halcmd print routines broke xhc-hb04.
This will tell the tcl code if a pin exists, removing the need for the
previous convoluted parsing of the stdout output.
The actual search routine has been changed from a list walking legacy one,
to use the `halg_foreach()` iteration model
Fixes #1161 
=> Reinstate workaround to keep xhc-hb04 pendants working

src/hal/i_components/message.icomp, src/hal/i_components/messagev2.icomp
They were converted using a predecessor of the current mechanism
=> Update message and messagev2 to use argc/argv string passing correctly

src/machinetalk/haltalk/haltalk_command.cc
Follow up to https://github.com/machinekit/machinekit/pull/1172
@ArcEye I did take another close look at the haltalk_command code and fixed more potential problems. I think we need to do a complete review at some point.
=> Haltalk command cleanup

src/machinetalk/include/halpb.hh, src/machinetalk/lib/mk_service.cc, src/rtapi/rtapi_msgd.cc
Another set fixes for problems reported by Coverity Scan
=> Coverity fixes part2

src/hal/lib/hal.h, src/hal/lib/hal_lib.c, src/hal/lib/hal_ring.c, src/machinetalk/msgcomponents/ringread.comp
Here is the third set of fixes for problems reported by Coverity Scan affecting HAL.
=> Fixes for problems reported by Coverity Scan

README.md
=> Remove stray readme.md from machinekit-multicore testing phase

.jenkins/manual_upload.sh
Script used in Jenkins for upload of generated manual-pages package
=> Add required jenkins script

src/hal/lib/hal.h, src/hal/lib/hal_comp.c, src/hal/lib/hal_funct.c, src/hal/lib/hal_lib.c, src/hal/lib/hal_param.c, src/hal/utils/halcmd_commands.c, src/hal/utils/halcmd_rtapiapp.cc, src/machinetalk/haltalk/haltalk_command.cc, src/machinetalk/lib/mk_service.cc, src/machinetalk/support/unionread.c, src/rtapi/rtapi_app.cc, src/rtapi/rtapi_support.c
The warnings are quite annoying on Ubuntu 14.04.
@ArcEye Can you please review this PR.
=> fix compiler warnings (printf security)

src/hal/lib/halpb.cc, src/machinetalk/haltalk/haltalk_command.cc, src/machinetalk/haltalk/haltalk_rcomp.cc, src/rtapi/shmdrv/Submakefile
Contains the non-functional code cleanups in Haltalk executed as part of https://github.com/machinekit/machinekit/pull/1188
=> Haltalk code cleanup

configs/ARM/BeagleBone/MendelMax-CRAMPS/CRAMPS.ini, configs/ARM/BeagleBone/MendelMax-CRAMPS/mendelmax.py
Reported recently in the mailing list.
=> configs: fix MendelMax-CRAMPS config

src/hal/lib/hal_comp.c
This was a bottleneck with rcomps validating pins.
Potentially reduce overhead by 50% where the owning comp is an instance,
by checking these first rather than legacy comps
=> Reorder the checks in halpr_find_owning_comp

src/hal/drivers/hal_pru_generic/Submakefile
See https://github.com/machinekit/machinekit/issues/1182#issuecomment-288459214
=> hal_pru_generic: enable build for RT-PREEMPT

src/emc/rs274ngc/previewmodule.cc, src/machinetalk/haltalk/haltalk_command.cc, src/machinetalk/haltalk/haltalk_group.cc, src/machinetalk/haltalk/haltalk_introspect.cc, src/machinetalk/haltalk/haltalk_rcomp.cc, src/machinetalk/include/pbutil.hh, src/machinetalk/lib/pbutil.cc
Continuation of https://github.com/machinekit/machinekit/pull/969
@ArcEye Can you please take a look at this patch.
I still need verify if the FAST road also works.
=> Deprecate send container string dest

src/hal/i_components/indextablev2.icomp
This component is meant for controlling an indexing table.
=> indextablev2.icomp: add indextable component

src/hal/drivers/mesa-hostmot2/pktuart.c
-- this change is backwards compatible to older MESA VHDL
`int hm2_pktuart_setup(char *name, int bitrate, s32 tx_mode, s32 rx_mode, int txclear, int rxclear)` :  function signature remains unchanged.
FilterReg value is calculated according to `floor((0.5*BitTime*ClockLow - 1))` .
An expert user can pass his own 8 bit filter value as bits 22..29 of `rx_mode`. 
See also https://forum.linuxcnc.org/27-driver-boards/32811-mesa-digital-filters 
and https://github.com/machinekit/machinekit/issues/877#issuecomment-302886330
=> Added Packet UART 8 bit filter option

src/hal/i_components/maxn.icomp, src/hal/i_components/maxnv2.icomp, src/hal/i_components/minn.icomp, src/hal/i_components/minnv2.icomp, src/hal/i_components/sumn.icomp, src/hal/i_components/sumnv2.icomp
This patch adds a few new HAL components.
Sponsored by [Nectar 3D](http://nectar3d.com/).
=> components: add maxn, minn and sumn

src/emc/tp/blendmath.c, src/emc/tp/blendmath.h, src/emc/tp/tc.c, src/emc/tp/tp.c
This PR backports changes in the TP from LinuxCNC which did not make into Machinekit.
=> Backport TP patches from upstream LinuxCNC

src/Makefile, src/hal/user_comps/huanyang-vfd/README.md, src/hal/user_comps/huanyang-vfd/Submakefile, src/hal/user_comps/huanyang-vfd/config-files/custom.hal, src/hal/user_comps/huanyang-vfd/config-files/custom_postgui.hal, src/hal/user_comps/huanyang-vfd/config-files/panel.xml, src/hal/user_comps/huanyang-vfd/hy_comm.c, src/hal/user_comps/huanyang-vfd/hy_comm.h, src/hal/user_comps/huanyang-vfd/hy_vfd.c
A user space component for controlling a huanyang spindle inverter with machinekit.
Component originally written by S Alford and published at
http://www.cnczone.com/forums/phase-converters/91847-huanyang-vfd-rs485-modbus-3.html#post704008
Changes were contributed to fix problems with the rebranding of emc2 to linuxcnc.
These were contributed by alan_3301, also on the cnczone forum.
Seb Kuzminsky <https://github.com/SebKuzminsky> added the code to the Linuxcnc repo and made
numerous changes, edits and bugfixes including:
Creating a Submakefile so as to build within the source tree
Ensuring clean shutdown
Fixed frequency calculation
Improved comms error handling
Read retry if initial one fails
Added spindle speed pins
Enabled setting params from command line
Fixed partial reads bug
Brian …
=> Add hy_vfd to Machinekit repo

configs/sim/axis/hy_vfd/README, configs/sim/axis/hy_vfd/axis_mm.ini, configs/sim/axis/hy_vfd/core_sim.hal, configs/sim/axis/hy_vfd/hy_vfd-postgui.hal, configs/sim/axis/hy_vfd/hy_vfd.glade, configs/sim/axis/hy_vfd/hy_vfd.hal, configs/sim/axis/hy_vfd/simulated_home.hal, src/hal/user_comps/huanyang-vfd/config-files/README
Donated by Otto Meister <42qwertzu@gmail.com>
=> Add sim config for haunyang_VFD modbus/RS485 spindle drive

src/emc/usr_intf/halui.cc
Omitted from @machinekoder PR #1091 and not noticed until now
=> Add rapid override pins to halui

src/hal/i_components/demux16.icomp, src/hal/i_components/demux16v2.icomp
Adapted from components (c) Les Newell <lesATsheetcamDOTcom>
=> Add demux16 and demux16v2 components to instantiated components.

src/hal/drivers/mesa-hostmot2/sserial.c, src/hal/drivers/mesa-hostmot2/sserial.h
Pull request regarding issue https://github.com/machinekit/machinekit/issues/1250
=> adding float support for sserial.

src/hal/user_comps/hal_temp_bbb.py
as per solution of @darenschwenke
https://groups.google.com/d/msg/machinekit/RrNLUo4ASP4/77ve-fdQBgAJ
relates to https://github.com/machinekit/machinekit/issues/1238
=> hal_temp_bbb: fix path for ADC

configs/hm2-soc-stepper/5i25-soc-cramps.ini
=> 5i25-soc-cramps.ini: fix firmware config path

src/hal/components/hal_pru.c, src/hal/components/hal_prudebug.c, src/hal/drivers/hal_pru_generic/hal_pru_generic.c, src/hal/support/pru/__prussdrv.h, src/hal/support/pru/prussdrv.c, src/hal/support/pru/prussdrv.h
This PR ports back a selection of relevant fixes from the upstream pruss driver:
https://github.com/beagleboard/am335x_pru_package
=> Hal pru generic update

src/machinetalk/config-service/configserver.py, src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/mklauncher/test_mklauncher.py, src/machinetalk/proto/setup.py, src/machinetalk/proto/src/machinetalk/protobuf/config.proto, src/machinetalk/proto/src/machinetalk/protobuf/types.proto
This PR adds support for launcher importance to mklauncher. The feature can be used to implement user based favorites on the client.
=> Mklauncher: add support for importance/favorites

src/machinetalk/mklauncher/mklauncher.py
update for https://github.com/machinekit/machinekit/pull/1271
=> mklauncher: fix incremental update problem

src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/mklauncher/test_mklauncher.py
Update the mklauncher to use Pythonic snake-case naming.
=> mklauncher: use pythonic naming

src/machinetalk/webtalk/webtalk.hh, src/machinetalk/webtalk/webtalk_echo.cc, src/machinetalk/webtalk/webtalk_main.cc, src/machinetalk/webtalk/webtalk_pbzws_policy.cc, src/machinetalk/webtalk/webtalk_wsproxy.cc
Fixes issue discussed at https://github.com/machinekit/machinekit/issues/1152#issuecomment-336050599
=> Czmq4 - additional API changes for webtalk

debian/armhf.postrm.in, debian/rules.in
=> Fix upgrade

src/emc/rs274ngc/interp_convert.cc, src/emc/rs274ngc/interp_queue.cc, src/emc/rs274ngc/interp_queue.hh
This is old work that I did about 11 months ago. It has been running happily that entire time, I just never issued a PR. Reference Issue #1055.
=> Allow motion output control while cutter comp is enabled (#1055)

src/emc/iotask/ioControl.cc
With nonrandom toolchanger, previously this pin showed the internal array
index, but it should be the P word from the tool table instead.
See https://github.com/machinekit/machinekit/issues/1314
=> Fix incorrect values on iocontrol.0.tool-prep-pocket

pkg/rpm/README.md, pkg/rpm/machinekit.spec
here is a short instruction https://github.com/Shaeto/machinekit/blob/rpmbuild/pkg/rpm/README.md
i can provide access to the test (armv7hl) repository
think this spec file can be used for other architectures (atm tested only under arm) and can be added to official Fedora collection of packages
=> Add support for building a RPM package.

src/hal/drivers/cpuinfo.c
Fixes #1223 (https://github.com/machinekit/machinekit/issues/1223#issuecomment-387739491)
=> Add new Rpi3B revision numbers to have them recognised.

src/hal/utils/halcmd_commands.c
=> Halcmd ringbuffer options error, does not list all options.

debian/control.buster.in, debian/control.sid.in, debian/control.stretch.in
python-gtksourceview2 and python-gst-1.0 available in all 3 now
=> Adjust deps for Stretch, Buster and sid.

scripts/linuxcnc.in
cherry-pick improvement for https://github.com/machinekit/machinekit-cnc/issues/44
also see https://github.com/machinekit/machinekit-cnc/pull/54
=> scripts/linuxcnc.in: more meaningful instructions

src/hal/drivers/mesa-hostmot2/capsense.c, src/hal/drivers/mesa-hostmot2/encoder.c, src/hal/drivers/mesa-hostmot2/hm2_7i43.c, src/hal/drivers/mesa-hostmot2/hm2_7i90.c, src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h, src/hal/drivers/mesa-hostmot2/hostmot2.c, src/hal/drivers/mesa-hostmot2/hostmot2.h, src/hal/drivers/mesa-hostmot2/ioport.c, src/hal/drivers/mesa-hostmot2/pwmgen.c, src/hal/drivers/mesa-hostmot2/resolver.c, src/hal/drivers/mesa-hostmot2/sserial.c, src/hal/drivers/mesa-hostmot2/sserial.h, src/hal/drivers/mesa-hostmot2/tp_pwmgen.c, src/hal/drivers/mesa-hostmot2/watchdog.c
Follow up to https://github.com/machinekit/machinekit/pull/1414
=> Convert hm2 params to pins

src/hal/user_comps/xhc-whb04b-6/hal.cc, src/hal/user_comps/xhc-whb04b-6/hal.h, src/hal/user_comps/xhc-whb04b-6/pendant.cc
Add toggle function for Mist/Flood/Lube
Mist attached to macro16
Flood attached to macro15
Lube attached to macro2
=> Add toggle function for Mist/Flood/Lube

src/hal/user_comps/xhc-whb04b-6/hal.cc, src/hal/user_comps/xhc-whb04b-6/hal.h, src/hal/user_comps/xhc-whb04b-6/pendant.cc
Hi
Sorry for this but for the author have change the way for do this and now this is obsolete.
Have a nice day, best regards
https://github.com/machinekit/machinekit/pull/1436
=> Revert pr 1434

src/emc/iotask/ioControl.cc
New version has 4 extra pins but if not used functions as previously.
Allows a toolchanger or user to update the current tool in the ATC
to the system, so that it is displayed in the GUI and known to NML.
=> Altered version of ioControl.cc to update tool on homing ATC (CNC)

lib/python/machinekit/service.py, src/machinetalk/mklauncher/mklauncher.py, src/machinetalk/mkwrapper/mkwrapper.py
* fix PEP8 naming issues
* simplify `update_io` function
=> Fix leftovers from Machinetalk Python cleanup

debian/control.buster.in, debian/control.sid.in, debian/control.stretch.in
=> Add dep uuid-runtime for Stretch and above, missed in original.

src/hal/drivers/hal_bb_gpio/hal_bb_gpio.c, src/hal/drivers/hal_pru_generic/stepgen.c
Fixed some more occurrences of rtapi_print affected by change of RTAPI_MSG_ERR to RTAPI_MSG_ALL.
=> Fixed some more occurrences of rtapi_print affected by logging fix.

src/hal/drivers/hal_bb_gpio/hal_bb_gpio.c
This is a bug fix.  Can it go into the main MK repo?  Thanks!
----
Thanks to @mlampert for identifying and reporting this, and @cdsteinkuehler for pointing out where to fix.
https://groups.google.com/forum/#!topic/machinekit/_RJ63TNH39k
https://github.com/machinekit/machinekit/issues/1481
=> hal_bb_gpio:  Fix input pins for PocketBeagle

debian/extras/usr/share/linuxcnc/udev/99-xhc-whb04b-6.rules, debian/machinekit-posix.install.in, debian/machinekit-rt-preempt.install.in, debian/machinekit-xenomai.install.in, src/hal/user_comps/xhc-whb04b-6/README.md, src/hal/user_comps/xhc-whb04b-6/hal.cc, src/hal/user_comps/xhc-whb04b-6/hal.h, src/hal/user_comps/xhc-whb04b-6/pendant.cc
Hi
Regarding to this PR https://github.com/machinekit/machinekit-hal/pull/202
You says : 
I will probably backport this to machinekit too, as it maintains an existing element of the code.
_Originally posted by @ArcEye in https://github.com/machinekit/machinekit-hal/pull/202#issuecomment-491305336_
=> WHB04B-6 pendant update readme and missing rules file
