src/hal/drivers/mesa-hostmot2/hm2_7i90.h

cpp stringification created an invalid descriptor when using
parentheses

hal/drviers/7i90: unbreak loading of the driver

---

src/emc/rs274ngc/interp_convert.cc
src/emc/rs274ngc/interp_internal.hh
src/emc/rs274ngc/rs274ngc_pre.cc

Also add an ini file field and allow user variance of arc tolerances
within preset limits
Default tolerance set to figure 2 * 0.001 * sqrt(2) for inch,
and 2 * 0.01 * sqrt(2) for mm.
This would mean that any valid arc where the endpoints and/or
centerpoint got rounded or truncated to 0.001 inch or 0.01 mm
precision would be accepted.
This behavior is the root of the problem with some CAM generated code.
Minimum tolerance capped at 1 micron and equivalent imperial.
Now passes all tests ( 139 of 139 )
Previous problem was solely related to the tests themselves.
Because they invoke the interpreter via bin/rs274 without an ini file, a valid tolerance figure
was not being set - now fixed with default value irrespective of how invoked.
Signed-off-by: Mick Grant<arceye@mgware.co.uk>

Fix metric arc tolerence to same value as imperial

---

lib/python/machinekit/launcher.py

This bug prevented correct cleanup in case linuxcnc or other started processes fail on start-up. A error is now raised to make handling possible,

machinekit/launcher: fixed unchecked exit when started process fails

---

debian/machinekit.postinst

Follow Debian policy and use invoke-rc.d to trigger rsyslogd restart
Resolves machinekit/machinekit#447

debian: Use invoke-rc.d in machinekit.postinst

---

scripts/linuxcnc.in

This reverts commit d337feba8e2a2d2f8143fa0b6f7fefa92634c2c4.
This patch partially reverts https://github.com/machinekit/machinekit/pull/424. Environment variable replacement should not be done in the linuxcnc script. In fact the patch affected all linuxcnc instances as eval does not only replace environment variables but also local variables and quote marks.

Revert "linuxcnc: added environment variable replacement for ini files"

---

lib/python/pyvcp_widgets.py

Bug in radio button widgets
initval field setting the correct widget to active at initialisation, but changes to prevent
unnecessary updates supressing initial setting of associated pin to match.
Explicitly setting pin associated with active button selection via initval at initialisation corrects this.

Bug fix - pyvcp_widgets

---

scripts/gcode-to-ngc
src/Makefile

Adds a script to convert RepRap flavour gcode files to Machinekit flavour ngc files. 
Idea is to use it with program extension support of user intefaces.

fdm: added gcode-to-ngc script

---

man/man9/motion.9
src/emc/motion/command.c
src/emc/motion/mot_priv.h
src/emc/motion/motion.c

Fix for the motion IO pin issue: https://github.com/machinekit/machinekit/issues/451
Uses a similar approach to fix the problem that outputs are driving a signal as the out-io pin of the lincurve component: https://github.com/machinekit/machinekit-man/blob/master/man9comp/lincurve.9comp.asciidoc#pins

Add IO to motion output  pins

---

src/emc/motion/mot_priv.h
src/emc/tp/tp.c

fixes https://github.com/machinekit/machinekit/issues/467
On 32bit systems the default number data type is a 32bit integer. Therefore, shifting such a number more than 31 bits to the left does not work correctly. For such machines it is necessary to explicitely specify the data type of the number. In this case `ull` for unsigned long long which is a 64bit unsigned integer and matches the data type of the mask registers.

TP fix missing typecasts for I/O mask registers

---

src/emc/rs274ngc/previewmodule.cc

fixes a problem in the previemodule introduced by https://github.com/machinekit/machinekit/pull/472

emc/rs274ngc/previewmodule: added missing UPDATE_TAG

---

nc_files/remap-subroutines/fdm/g22.ngc
nc_files/remap-subroutines/fdm/g23.ngc

The name of the ini parameter has changed to match the RETRACT_VEL parameter.

fdm-remaps: fixed outdated ini parameter name

---

src/configure.in
src/hal/user_comps/hal_temp_bbb.py

Added  -b argument to hal_temp_bbb to support both BoBePr and CRAMPS cape
Mostly by adding adc2r code from:
https://github.com/modmaker/machinekit/blob/master/configs/ARM/BeagleBone/CRAMPS/ReadTemp.py
If the -b option is not used BeBoPr is selected as default, as in the original file

BBB temp readout additional cape support

---

configs/ARM/BeagleBone/CRAMPS/CRAMPS.hal

configs: Add missing board argument to CRAMPS.hal file

---

src/hal/lib/hal.h
src/hal/lib/hal_funct.c
src/hal/lib/hal_lib.c
src/hal/lib/hal_param.c
src/hal/lib/hal_pin.c
src/hal/lib/hal_ring.c
src/hal/lib/hal_ring.h
src/rtapi/ring.h

this is fallout from the work with Bas on the delayline component
the first two are backwards-compatible extensions of the ring API
the second two are convenience helpers:  make generic pin/param creation, funct export, and ring ops work printf-style as well - this should get rid of a ton of rtapi_snprintf() code needed; sometimes the obvious is missing.

HAL + RTAPI fixes

---

src/hal/components/hbridge.comp

recently used in a servo demo with PRU PWM - other than the stock pwmgen component those dont need
a base thread

hal/comps: hbridge - generate PWM driving values for an H-bridge

---

lib/python/machinekit/launcher.py
src/rtapi/rtapi_app.h

thanks to the arcane code in halcmd.

machinekit/launcher.py: fix inifile passing to halcmd

---

src/emc/task/emccanon.cc
src/emc/tp/blendmath.c
src/emc/tp/tc.c
src/emc/tp/tc.h
src/emc/tp/tp.c
src/emc/tp/tp_shared.h

These commits from me and Chris Radek un-break blending. This branch also fixes some emcmotStatus fields, which were not properly set to default values when the motion queue is empty.

TP Fixes ported from LinuxCNC 2.7.0~pre5

---

src/configure.in

This enables usage of the Xenomai RTDM API from HAL RT components
(xenomai-user flavor only), for instance RT-CAN.
Compiling such components will need an extra
RTFLAGS += backtick xeno-config --skin native --cflags backtick
to get at the Xenomai headers.
No functional changes, and no impact expected.
Test PR to see what the buildbot has to say on this.

BUILDBOT TEST: xenomai-usr/build: link -rtdm into rtapi_app

---

share/axis/tcl/axis.tcl
src/emc/usr_intf/axis/scripts/axis.py
src/emc/usr_intf/axis/scripts/debuglevel.py
src/emc/usr_intf/axis/scripts/linuxcnctop.py
src/emc/usr_intf/axis/scripts/teach-in.py
tcl/bin/emccalib.tcl
tcl/bin/pickconfig.tcl

Picked up most but no doubt not all of the instances of `LinuxCNC` in titles of windows related to Axis.
Also fixed the annoying habit of Axis of opening a webbrowser on `http://www.linuxcnc.org` when Help-> About Axis is selected.

more cosmetic rebranding of Axis

---

lib/python/machinekit/launcher.py

Realtime stop called by the launcher script collided with stopping the linuxcnc script. Therefore, this patch makes the launcher script call realtime stop only when a realtime start was called previously.

lib/machinekit/launcher: fix for annoying bug in run scripts

---

src/rtapi/rtapi_global.h
src/rtapi/rtapi_msgd.cc

using tp debugging has shown we're scratching the limit, so increase to 512k:
before, tp debugging on (extreme usage):
Mar 24 17:53:43 nwheezy msgd:0: log buffer hwm: 122% (4105 msgs, 288318 net bytes out of 262144)
just realtime start+stop:
Mar 24 17:54:13 nwheezy msgd:0: log buffer hwm: 0% (17 msgs, 1138 net bytes out of 262144)

msgd: log logbuffer highwater mark on exit, increase size

---

configs/ARM/BeagleBone/BeBoPr++/Pololu/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr++/Pololu/lineardelta.ini
configs/ARM/BeagleBone/BeBoPr-Bridge/velocity-extruding/lineardelta-vel-extr.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/velocity-extruding/lineardelta-vel-extr.ini
configs/ARM/BeagleBone/CRAMPS/CRAMPS.ShuttleXpress.ini
configs/ARM/BeagleBone/Probotix/Comet_Metric.ini
configs/ARM/BeagleBone/Xylotex/Xylotex.ShuttleXpress.ini

Some example configuration files still used the older path values
for PRUBIN, which only work with run-in-place.  Updated so package
based installs will work properly as well.

configs: Update all example configs to use proper PRUBIN path

---

src/emc/tp/tp.c

The bad behavior in master:
* Pause causes immediate feedhold, even during spindle sync
* ...spindle position disparity grows
* resume = surge forward due to large error, causing following error
The fixed behavior (matching linuxcnc 2.6):
* On pause, feedhold is deferred until after synced section is done
* Abort is still immediate as before

tp: fix for pause during spindle synced motion regression from 2.6

---

src/hal/cython/Submakefile
src/hal/utils/halcmd_commands.c
src/hal/utils/halcmd_main.c
src/hal/utils/halcmd_rtapiapp.cc
src/machinetalk/include/pbutil.hh
src/machinetalk/lib/pbutil.cc
src/rtapi/rtapi_app.cc
src/rtapi/rtapi_compat.c
src/rtapi/rtapi_compat.h

this was appalling to start with, time to fix.
The halcmd output now looks like so:
mah@nwheezy:~/machinekit-prepare/src$ halcmd -f -k
halcmd: loadrt or2
<stdin>:1: Realtime module 'or2' loaded
halcmd: loadrt doesnotexist
<stdin>:3: insmod failed, returned -1:
do_load_cmd: dlopen: doesnotexist.so: cannot open shared object file: No such file or directory
rpath=/home/mah/machinekit-prepare/rtlib/posix:/home/mah/machinekit-prepare/lib
See /var/log/linuxcnc.log for more information.

improve rtapi_app + halcmd loadrt/unloadrt error message reporting

---

src/emc/kinematics/genserkins.c

Since these kins are generated, this was lost in migration

kins/genserkins: export as vtable

---

src/hal/lib/hal_funct.c

otherwise easily exceeds the limits of HAL name length (41)

hal library/thread: shorten tmax-increased to tmax-inc

---

debian/machinekit.postinst

Correct /machinekit dir or symlink creation
for installation by package
Set home using $SUDO_USER
signed-off-by: Mick <arceye@mgware.co.uk>

Machinekit re-branding - bugfix

---

debian/machinekit.postinst
scripts/linuxcnc.in

The creation of the ~/machinekit dir, or the creation of a symlink
to the pre-existing ~/linuxcnc dir, is now left until the linuxcnc
script is run
This not only ensures that the $HOME env var points to the actual users
home dir and not root, when sudo is used to install,
but caters for multiple and or additional users on one machine, creating new dirs /
symlinks on the fly as required
Resolves issue #564 and issue #541

Fix ~/machinekit dir creation problem

---

configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper-DecaMux.ini

A further addition to #580, just changes the .ini to designate the correct PRU binary when using a DECAMUX with two PEPPERs.

Change PRU binary designation for DECAMUX support

---

src/hal/cython/machinekit/rtapi.pyx

This allows using keyword parameters to call the `loadrt` and `newinst` functions e.g.
```python
rt.loadrt('and2', count=5)
```
without this path only string parameters are possible;
```python
rt.loadrt('and2', 'count=5')
```

RTAPI Cython API: allowing kwargs for loadrt and newinst

---

lib/python/machinekit/service.py
src/machinetalk/config-service/configserver.py
src/machinetalk/haltalk/haltalk.hh
src/machinetalk/haltalk/haltalk_main.cc
src/machinetalk/haltalk/haltalk_zeroconf.cc
src/machinetalk/messagebus/messagebus.cc
src/machinetalk/mkwrapper/mkwrapper.py
src/machinetalk/webtalk/webtalk_zeroconf.cc
src/rtapi/rtapi_msgd.cc

This patch fixes a problematic behaviour of machinetalk announcing local ip addresses. Using the local hostname the address can be resolved correctly (IPv4 or IPv6). This approach is similar to what network printers do.

Use hostnames in service announcement

---

src/hal/lib/hal_instance.c
src/hal/lib/hal_priv.h

Intended to simplify critical region coding. 
The full story is at: https://github.com/mhaberler/asciidoc-sandbox/wiki/Locking-and-using-scoped-locks-with-the-HAL-C-API (needs to go to the yet-unwritten HAL manual )

Halmutex macro

---

src/Makefile
src/machinetalk/mklauncher/Submakefile
src/machinetalk/mklauncher/mklauncher.py

This PR adds a new machinekit module. Mklauncher is the remote equivalent to the linuxcnc/machinekit configuration dialog. The intended use is to start machinetalk based Machinekit configurations remotely and to provide access to the available configurations via the new "launcher" service.

machinetalk: mklauncher

---

nosetests/test_netcmd.py
src/hal/cython/machinekit/hal_signal.pyx

this PR renames the `new_sig` function of the new HAL Python API to `newsig` to keep naming consistent with `halcmd` and other functions like `newthread` or `newpin`

python/machinekit/hal: renamed new_sig to newsig

---

debian/control.in

The offending commit added a dep `python (= 2.7)`, which of course
doesn't actually exist. Thanks to @strahlex for pointing out the exact
commit and line (#594, c3ce094)!

Fixup for c3ce094, debian/control.in

---

src/configure.ac

**MAINTAINERS**:  Please check the `d7-bb-pkg` build logs for the following lines before merging:
```
checking platform-pc... disabled for this architecture
checking platform-beaglebone... default enabled for this architecture
checking platform-raspberry... default enabled for this architecture
checking platform-zedboard... default enabled for this architecture
```
Thanks, @strahlex for pointing this out.
(Original commit message follows)
*****
When running `./configure` without `--host` and `--build`, the
`AC_CANONICAL_*` macros run `config.guess` to determine host and build
architectures.
Commit ccf3bc98b from #594 sets `--host` and `--build` to Debian
multi-arch names from variables defined in
`/usr/share/dpkg/architecture.mk` during package builds.
This exemplifies the difference: …

configure.ac:  account for Debian multi-arch

---

lib/python/machinekit/service.py
src/machinetalk/haltalk/haltalk_zeroconf.cc

- fixes a problem introduced by https://github.com/machinekit/machinekit/commit/d0f446c2471d6174648a8f03d148f0ca633c0f7e
- keeps naming of service announcments consistent
- explicitely specifying protocol and interface for announcements

Machinetalk service fixes

---

nosetests/test_ring.py
nosetests/test_ringdemo.py
nosetests/test_rtapi.py
nosetests/unittest_or2.py
src/hal/cython/machinekit/rtapi.pyx

to fp to keep the Python API consistent
halcmd's newthread function is called like `newthread name period fp` whereas the Cython function `newthread` had the paramter `use_fp`. To keep the API consistent I renamed the paramter to `fp`

python/machinekit/rtapi: renamed use_fp parameter 

---

debian/rules.in
src/Makefile

GNU coding standards say `make clean` shouldn't remove anything
generated by `./configure`.
This is a fixup for #600.  Fixes #621

Don't remove `machinekit.ini` during `make clean`

---

src/machinetalk/mkwrapper/mkwrapper.py

Binds the file service to all iterfaces as it should be done. Additionally fixes a problem with wrong usage of the printError function.

machinetalk/mkwrapper: fix for file service not working on some interfaces

---

debian/rules.in

Ignore `make` compiler defaults, improving default `CC`/`CXX` handling in packages, allowing e.g. `AC_PROG_CC` to select a multi-arch compiler like `x86_64-linux-gnu-gcc` rather than the `make` default `cc`.

debian/rules: Only pass CC/CXX from environment

---

src/configure.ac

The ShabbyX RTAI fork has a stub `rtai-config` script that detects (possibly multiple) installed RTAI versions and provides a way to select between them.
This patch checks for that style script if it exists, and otherwise assumes the old behavior.
A little bait for Maintainers:  once this is merged, I have a full set of Jessie packages to push out for testing!

configure.ac:  accommodate ShabbyX-style rtai-config

---

nc_files/remap-subroutines/fdm/m700.ngc

This patch renames the M600 GCode to M700 to prevent aliasing problems with the M600 GCode in the Marlin firmware

remap-subroutines/fdm: renamed M600 to M700

---

debian/configure
src/configure.ac
src/hal/lib/hal_lib.c

A few random fixes that prepare for Xenomai-3 and newer kernels, but don't really belong in such a PR.
- Packaging:  Fix kthreads specification
- `configure.ac`:  Fail if `--with-xenomai[-kernel]` requested but unconfigurable
- `hal_lib`:  Convert a couple of `vsnprintf` statements to `rtapi_vsnprintf`

Misc fixes

---

src/configure.ac
src/hal/lib/hal_procfs.c
src/rtapi/procfs_macros.h
src/rtapi/rtai-kernel.c
src/rtapi/rtapi_kdetect.h
src/rtapi/rtapi_proc.h
src/rtapi/xenomai-common.h
src/rtapi/xenomai-kernel.c
src/rtapi/xenomai-kernel.h
src/rtapi/xenomai.c

This adds support for newer RT kernels and run-time without breaking compatibility with current deps (Xenomai-2, RTAI-4.0, Linux-3.8.13).
Linux updates include @koppi's patch from PR #618.
See commit log for details.

Xenomai 3, RTAI 4.1, Linux >=3.10 updates

---

src/hal/i_components/bitslice.icomp
src/hal/i_components/gantry.icomp
src/hal/i_components/lgantry.icomp
src/hal/i_components/lincurve.icomp
src/hal/i_components/lutn.icomp
src/hal/i_components/multiswitch.icomp

6 components have predefined iprefix names, this will override the
name set in newisnt, unless iprefix=  is specified
Predefined iprefixes removed, the parameter can still be used if required,
but in most instances, setting the name via
'newinst [component-name] [new-instance-name] [args ....]'
will work better and in a more easily understood way.

Bugfix - instantiable components

---

configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper-DecaMux.hal
configs/ARM/BeagleBone/BeBoPr++/Pepper/BeBoPr++Pepper.hal
configs/ARM/BeagleBone/BeBoPr++/Pepper/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr++/Pololu/BeBoPr++.hal
configs/ARM/BeagleBone/BeBoPr++/Pololu/TAKE-5.hal
configs/ARM/BeagleBone/BeBoPr++/Pololu/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/velocity-extruding/lineardelta-vel-extr.hal
configs/ARM/BeagleBone/BeBoPr/BeBoPr.hal
configs/ARM/BeagleBone/PMDX-432/Shapeoko/Shapeoko.hal
configs/ARM/BeagleBone/PMDX-432/Standard-Configs/K9-Generic.hal
configs/ARM/BeagleBone/PocketNC/PocketNC.hal
configs/ARM/BeagleBone/Probotix/Comet.hal
configs/ARM/BeagleBone/Xylotex/Xylotex.hal

Recent changes to the PRU driver create HAL names that are too long with
the default driver name of hal_pru_generic.  This changes the driver
name to hpg and updates the example HAL files to match.

BeagleBone configs: Fix for HAL name length

---

src/hal/lib/halpb.cc

this caused a segfault as it didnt properly track the
changed semantics of the HAL instantiation API.
Alex - please verify this fixes the issue with haltalk before merging; I cannot reproduce the bug but I can smell it ;)

halpb.cc: fix reference to owning component

---

src/configure.ac

Setting `DEB_HOST_MULTIARCH` to the value detected by `config.guess`
will be wrong in many cases, and indeed breaks the multiarch
`tclConfig.sh` script on i?86:
$ dpkg-architecture -qDEB_HOST_MULTIARCH
i386-linux-gnu
$ ./config.guess
i686-pc-linux-gnu
$ dpkg-query -L tcl8.6-dev | grep tclConfig.sh
/usr/lib/tcl8.6/tclConfig.sh
/usr/lib/i386-linux-gnu/tcl8.6/tclConfig.sh
$ cat /usr/lib/tcl8.6/tclConfig.sh
#! /bin/sh
. /usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/tcl8.6/tclConfig.sh
Fixes #644

Fixup e94b7ad1:  Unbreak tclConfig.sh

---

src/machinetalk/include/pbutil.hh
src/machinetalk/lib/pbutil.cc
src/rtapi/rtapi_app.cc

this used to break at
loadrt hm2_pci config="num_stepgens=1 num_encoders=1"
as the space would break apart the arg
this patch mutates kmod args to explicitly quote with '
thanks to Amit for the patience

rtapi_app: properly quote kmod args

---

src/emc/kinematics/Submakefile
src/emc/rs274ngc/Submakefile
src/emc/sai/Submakefile
src/emc/task/Submakefile
src/emc/usr_intf/Submakefile
src/emc/usr_intf/axis/Submakefile
src/hal/user_comps/Submakefile
src/hal/user_comps/vfdb_vfd/Submakefile
src/hal/utils/Submakefile
src/libnml/Submakefile
src/libnml/posemath/Submakefile
src/rtapi/Submakefile

This patch https://github.com/machinekit/machinekit/commit/136de2e13f78ff50047248a0c6a3534305a21a72 changed the creating of the librtapi_math.so to a symlink. Apps and libraries still may need to be linked against to librtapi_math.so.0 to build packages correctly.

rtapi_math: linking to librtapi_math.so.0

---

debian/control.in
src/machinekitcfg.py-tmp.in
src/machinetalk/mkwrapper/mkwrapper.py

This PR does following things:
- removes the obsolete choose_netifaces function
- adds a linuxcnc.ini-like way to use config variables in Machinekit HAL configurations, note that the modules acts as singleton. Config variables can be passed to Python-HAL files.
example:
```python
from machinekit import config
config.load_ini('myconfig.ini')
import mypythonhalconfig
```
mypythonhalconfig.py
```python
from machinekit import config
from machinekit import hal
x = config.find('AXIS_0', 'SCALE')
hal.Pin('e0.scale').set(float(x))
```

Machinekit python config updates

---

src/hal/cython/machinekit/hal_compdict.pyx
src/hal/cython/machinekit/hal_component.pyx
src/hal/cython/machinekit/hal_inst.pyx
src/hal/cython/machinekit/hal_instdict.pyx
src/hal/cython/machinekit/hal_loadusr.pyx
src/hal/cython/machinekit/hal_net.pyx
src/hal/cython/machinekit/hal_pin.pyx
src/hal/cython/machinekit/hal_pindict.pyx
src/hal/cython/machinekit/hal_sigdict.pyx
src/hal/cython/machinekit/hal_signal.pyx
src/hal/cython/machinekit/rtapi.pyx

- adds a way to init RTAPI inside the module to use it as a singleton in Python based HAL configs
e.g.
```python
from machinekit import rtapi as rt
rt.ini_RTAPI()
import myconfig
```
myconfig.py
```python
from machinekit import rtapi as rt
rt.newinst('and2', 'and2.bla')
```
- partially backports newinst functionality from halcmd
- improves string representation and hal dictionaries
- using Instance and Component
- adds pin lists to instance and component
- net now also links lists of pins
- pins can now be linked with automatic signal creation:
```python
x = rt.newinst('and2', 'and2.test')
y = rt.newinst('and2', 'and2.test2')
x.pin('out').link(y.pin('in0'))  # creates sig and2-test-out
hal.net('and2.test.out', 'and2.test2.in0')
```

Python API updates

---

src/machinekitcfg.py-tmp.in

An update to https://github.com/machinekit/machinekit/pull/672 . Adds automatic type guessing to simplify usage in Python HAL configs (no explicit typecasting necessary)

python/machinekit/config: added type guessing to ini reader

---

src/hal/cython/machinekit/hal_loadusr.pyx
src/hal/cython/machinekit/hal_pin.pyx
src/hal/cython/machinekit/hal_signal.pyx

This patch adds another set of features to the HAL Python API:
- allows passing arguments to loadusr using Python kwargs
- more sane error message when trying to create a signal that already exists
- attaching to existing signals specifying the signal type (and raising an error if signal has different type)
- show the value of pin and signal in Python string representation
- fix signal linking

Python API updates 2

---

lib/python/machinekit/launcher.py
src/hal/cython/machinekit/hal_loadusr.pyx
src/hal/cython/machinekit/hal_net.pyx
src/hal/cython/machinekit/hal_signal.pyx
src/machinekitcfg.py-tmp.in

This patch includes following changes
- adapted install_comp for instcomps
- adding the init argument also to newsig
- cleaned up machinekitconfig.py -> whitespace, obsolete functions
- exposing machinekit.config variables to module space
- bugfix in hal_net
- bugfix in launcher
- bugfix config

Python API updates 3

---

src/rtapi/rtapi_math/Submakefile

since librtapi_math.so.X is linked into arbitrary userland binaries, it
makes no sense to restrict building to BUILD_SYS == USER_DSO
this broke kthreads builds for me (if ./configure --with-rtai-kernel, i.e. no other flavors)

rtapi_math: build userland shared library regardless of build flavor

---

src/hal/i_components/io_muxn.icomp
src/hal/i_components/led_dim.icomp
src/hal/i_components/safety_latch.icomp
src/hal/i_components/select8.icomp
src/hal/i_components/selectn.icomp

This PR adds 3 additional HAL components:
* io_muxn is a multiplexer gate for IO signals, useful for multiplexing config signals
* led_dim converts brightness to luminance for dimming LEDs
* safety_latch latches error signals with configurable healing, harm and latching behavior
* selectn select on of n outputs
* small code cleanup for select8 component

hal/i_components: added io_muxn, safety_latch and led_dim components

---

src/rtapi/rtai-kernel.c

not sure where this is coming from:
RTAI_VERSION <= 400 does not get me there with these includes:
mah@nwheezy:~/machinekit-tutorial/src$ grep -R _NR_FAULTS /usr/src
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/ipipe_base.h:#define IPIPE_NR_FAULTS		34
/usr/src/linux-headers-3.8-1-common-rtai.x86/arch/x86/include/asm/ipipe_base.h:#define IPIPE_NR_FAULTS		33
/usr/src/linux-headers-3.8-1-common-rtai.x86/include/linux/ipipe_base.h:#define IPIPE_FIRST_EVENT	IPIPE_NR_FAULTS
/usr/src/linux-headers-3.8-1-common-xenomai.x86/arch/x86/include/asm/ipipe_base.h:#define IPIPE_NR_FAULTS		34
/usr/src/linux-headers-3.8-1-common-xenomai.x86/arch/x86/include/asm/ipipe_base.h:#define IPIPE_NR_FAULTS		33
/usr/src/linux-headers-3.8-1-common-xenomai.x86/include/asm-generic/xenomai/hal.h:#def …

rtapi/rtai: robustify handling of HAL_NR_FAULTS

---

lib/python/machinekit/service.py
src/machinetalk/config-service/configserver.py
src/machinetalk/mklauncher/mklauncher.py
src/machinetalk/mkwrapper/mkwrapper.py
src/machinetalk/videoserver/videoserver.py

As discovered here https://github.com/strahlex/QtQuickVcp/issues/34#issuecomment-119962509 Avahi announces its own FQDN instead of the systems hostname. In case the local hostname does not match the Avahi hostname the client is never able to resolve correctly. 
This PR fixes the problem by using the FQDN reported by Avahi.

machinetalk: using FQDN for service announcements

---

src/hal/i_components/at_pid.icomp

fixes the missing return values in the `at_pid` component

hal/i_components/at_pid: fix missing return values

---

debian/control.rt-preempt.in

Fix machinekit-rt-preempt package kernel deps

---

src/rtapi/rt-preempt.c

all threads-related defs, data and code are RTAPI only.
The rtapi_init/rtapi_exit array handling code for RTAPI is useless (it
is not present in xenomai either since the modules are managed in rtapi_app as
DSO's and need no representation at the RTAPI level for user threads).
As a bonus, ID assignment is now consistent across flavors as all ID's
are assigned through rtapi_next_handle().
This patch part of the Haberler "Summer of Less Code" project ;)
Also in the pipe: src/hal/lib -2500 lines.

rtapi/rt-preempt: remove dead code, clarify RTAPI/ULAPI usage of data

---

src/machinetalk/proto/Makefile

to make upstream merge of machinetalk-protobuf possible

machinetalk-protobuf: added default PKG-CONFIG variable

---

src/hal/drivers/hal_pru_generic/pwmgen.c

after enabling a pru_pwm on bealebone with:
setp hpg.pwmgen.0x.out.0x.enable 1
Tyinig to disable the pwm again with
setp hpg.pwmgen.0x.out.0x.enable 0
leaves the output on instead
setp hpg.pwmgen.0x.out.0x.enable 0
Now turns pwm output off as it should
Tested on BBB + CRAMPS2 board

Fix: Beaglebone Black pru_pwm now turns off after setting  hpg.pwmgen.enable to 0 (Cleaned)

---

src/machinetalk/mkwrapper/mkwrapper.py

A few updates for mkwrapper specific to remote file handling (now supported by QtQuickVcp)
- removed automatic file deletion on shutdown
- added cd and mkdir permission to FTP user to allow better file browsing from client

Mkwrapper update: remote files

---

lib/python/machinekit/nosetests/rtapilog.py
nosetests/test_mk_hal_basics.py
nosetests/test_netcmd.py
nosetests/test_rtapi.py
nosetests/unittest_or2.py
src/hal/cython/machinekit/hal_net.pyx
src/hal/cython/machinekit/hal_sigdict.pyx
src/hal/icomp-example/README
src/hal/icomp-example/icomp.c
src/hal/icomp-example/lutn.c
src/hal/lib/hal_instance.c
src/hal/utils/halcmd_commands.c
src/hal/utils/halcmd_commands.h
src/hal/utils/halcmd_main.c
src/hal/utils/instcomp.g
src/machinetalk/msgcomponents/pbring-demo.hal
src/machinetalk/msgcomponents/pbring-demo.py
src/machinetalk/msgcomponents/pbring.c
src/rtapi/rtapi_compat.c
src/rtapi/rtapi_compat.h

this branch does:
- fix instcomp - issue with extra_inst_delete fixed thanks to Mick
- improve on the hal/icomp-examples
- make the machinetalk/msgcomponents/pbring,c/pbring-demo.hal use the instantiation feature
- fix a few nits in the Cython bindings, thanks to Alex
- fix a nit with instance deletion and HAL locking
this is basically the cython-fixes branch plus example improvements, but with the nosetest runtest deleted because it makes the RTAI build slave unhappy.

improve examples for instantiable components, instcomp fixes

---

src/machinetalk/mkwrapper/mkwrapper.py

Axis has a default `INCREMENTS` value so Mkwrapper should have one too.

machinetalk/mkwrapper: adding default INCREMENTS value

---

src/hal/i_components/out_to_io.icomp
src/hal/lib/hal.h
src/hal/lib/hal_group.c
src/hal/lib/hal_rcomp.c

see also: https://sourceforge.net/p/emc/bugs/428/
and thanks to type-casting until the cows come home, this was never detected

hal/types: hal_data_u unsigned was signed

---

scripts/linuxcnc.in

Will prevent chown operation from succeeding

Bug-fix, fix typo of trailing period in scripts/linuxcnc.in

---

lib/python/machinekit/launcher.py
src/hal/cython/machinekit/rtapi.pyx

A set of patches that fix problems and add features related to launching Python HAL configurations
- added support for .py files to lluncher.load_hal_file()
- prevent double execution of exit handler
- fix adding system functions to module when running rtapi.init_RTAPI()

Launcher updates

---

src/rtapi/xenomai.c

each RT comp which calls hal_exit() on unload eventually calls on
_rtapi_exit() - which is a per component-exit, not a shutdown-type call
unlocking the RT memory on comp exit is a pretty bad idea as it may make
rtapi_app susceptible to page stealing.
Signed-off-by: Michael Haberler <git@mah.priv.at>

xenomai-user: do not unlock RT memory on module exit

---

scripts/latency-test

Was fixed in Linuxcnc in 2014, having existed for 7 years there
Probably has little effect, because only employed if period specifier not used, but should not be there.

Fix typo in latency-test script

---

configs/ARM/BeagleBone/Probotix/Comet.hal

Fix an errant [PRUCONF](DRIVER) entry missed when changing the
hal_pru_generic driver basename to hpg.

configs: Fix Probotix Comet Config

---

scripts/linuxcnc.in

Fixes a problem and potential security risk of running a shell
replacement over the INI file. The patch was accidentally introduced in
a re-branding operation.
See https://github.com/machinekit/machinekit/issues/754

scripts/linuxcnc: remove environment variable replacement

---

src/emc/task/emccanon.cc

canon: fix bug , non-NCD arcs on machines with ABCUVW axes
Arcs in the XY plane that fail Naive CAM collapsing would
accidentally convert the ABCUVW destination from program coordinates to
canonical coordinates twice, and get ridiculous endpoints as a result.
Thanks to Todd Zuercher for the bug report.

canon: fix bug , non-NCD arcs on machines with ABCUVW axes

---

src/machinetalk/include/czmq-watch.h
src/machinetalk/include/ll-zeroconf.hh
src/machinetalk/include/mk-zeroconf-types.h
src/machinetalk/include/mk-zeroconf.hh
src/machinetalk/lib/czmq-watch.c
src/machinetalk/lib/ll_zeroconf_register.cc
src/machinetalk/lib/mk_zeroconf.cc
src/machinetalk/lib/zeroconf_resolve.cc
src/machinetalk/lib/zeroconf_resolve_test.cc

I was asked to relicense as non-GPL
while at it, relicense as MPL2.0 so it could be integrated into czmq

czmq-watch.c/h: change license to MPL 2.0

---

src/machinetalk/config-service/configserver.py
src/machinetalk/mklauncher/mklauncher.py
src/machinetalk/mkwrapper/mkwrapper.py

This patch contains following fixes:
- fixes socket types in mklauncher and mkwrapper (ROUTER and not DEALER)
- fixes small lock usage in mkwrapper
- use nonblocking send functions
- adds multiprocessing for the preview service in mkwrapper to fix timeout problems

Mkwrapper and Mklauncher multiprocessing and ZMQ patterns

---

configs/by_interface/parport/plasma-thc-sim/estop.hal
configs/by_interface/parport/stepper-gantry/estop.hal
configs/by_interface/pico/USC_encod/univstep_load.hal
configs/by_interface/pico/ppmc/ppmc_load.hal
configs/by_interface/pico/ppmc_vel/ppmc_load.hal
configs/by_interface/pico/univpwm/univpwm_load.hal
configs/by_interface/pico/univpwmv/univpwm_load.hal
configs/by_interface/pico/univstep/univstep_load.hal
configs/by_machine/tormach/pcnc-1100.hal
configs/by_machine/tormach/pcnc-770.hal

instcomp does not convert C style underscores in component names to dashes
This affects 10 components, but only estop_latch is used in sample
configs in a way that requires alteration
The others either actually name the component (shuttlexpress) or having loaded it
do nothing further with it (demo_mazak)

Amend sample configs to reflect change in estop_latch component name.

---

src/hal/utils/instcomp.g

Change pin printout to use comp_name, so that where C style underscore
is present in name, it matches actual component and pin names.
2nd stage to #772 (b470e9ac360b50c8bbdd87cc4717957d7862a433)

Minor alteration to instcomp to correct man file component names.

---

src/hal/utils/instcomp.g

Force double spacing after troff section header to aid conversion
into asciidoc format
Resultant conversions and generated docs at
https://github.com/machinekit/machinekit-docs/pull/41

Further man page tidy up.

---

src/hal/i_components/lincurve.icomp
src/hal/utils/comp.g
src/hal/utils/instcomp.g

Additional 'Error :' text added to fatal error messages in both
so that they stand out amoungst general build output

comp and instcomp changes to check component name is same as filename

---

tests/hm2-idrom/skip

I left some debug cruft in e5fe2053; this patch removes it.

Remove debug info forgotten in e5fe2053

---

scripts/realtime.in
src/rtapi/rtapi_app.cc
src/rtapi/rtapi_msgd.cc

`syslog_async()` behaves strangely when logging to stderr with a 1s
`log_delay` and no syslog daemon: Initial logs are printed as
expected, but once the backlog buffer fills, a single log message is
printed only once per second.
This patch papers over the problem by setting `log_delay` to 0 when
logging to stderr.  If timing in sections of code calling
`syslog_async()` are at all critical, then this isn't a general fix,
since a slow syslog daemon would introduce latency into the call.
This patch also plumbs a `rtapi_app -s` option like `rtapi_msgd -s`,
and when the `SYSLOG_TO_STDERR` environment variable is set, the
`realtime` script adds that option to both daemons.
This problem can be reproduced by running a HAL configuration in debug
mode with no running syslog daemon, a common …

rtapi_app/msgd:  Fix logging to stderr

---

debian/configure
src/emc/motion/emcmotcfg.h
src/emc/tp/tc_types.h
src/emc/tp/tp.c

tc_types.h, tp.c:
Original dio_mask is with type of iomask_t, which is 64 bits.
For system with more than 64 bits of DIOs, we need to replace it
with RTAPI_BITIOPS defined at rtapi_bitops.h
emcmotcfg.h: set EMCMOT_MAX_DIO as 128

Implement dio_mask with RTAPI_BITOPS for 64+ bits of DIOs

---

src/hal/classicladder/files_project.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.

Cleaning up #ifdefs that break statements

---

.travis.yml
.travis/build_rip.sh
.travis/docker_run.sh
.travis/run_tests.sh
.travis/runtests.sh

This allows TravisCI to build Machinekit on an amd64 environment and run
the regression tests.
It does this using a Docker container to get a reproducable build
environment for a 64-bit host. Inside the container it uses proot/chroot
to actually do the building and testing.
The current structure is set up this way to have a general structure
that runs on x86_64 hosts which can build for amd64, i386 and ARM
environments.
Many thanks to @kinsamanka for making this possible.
Relates to #791.
Please do not merge this change yet. Travis should show up in this PR once it has been set up correctly (and I do another dummy push).

added TravisCI instructions for regression tests

---

.travis.yml

This will notify about Travis build status on
https://gitter.im/machinekit/machinekit
An example of this can be found here (to the right under 'Activity'): https://gitter.im/bobvanderlinden/machinekit

added gitter integration for travis-ci

---

.travis.yml

When forks of machinekit/machinekit used Travis, build notifications would show up on machinekit/machinekit's gitter. This is because `.travis.yml` would trigger notifications to machinekit/machinekit's gitter. Now that we have a gitter webhook-url saved as a private environment variable in Travis, we can use that variable in the `.travis.yml` file. That way no-one will know the gitter webhook-url, except for Travis and maintainers.
This patch is similar to what [others](https://github.com/meanjs/mean/pull/1004) have done after finding the same problem.

travis: use an environment variable for the gitter webhook

---

.travis.yml
.travis/build_deb.sh

This ensures that xenomai and rt_preempt builds are tested. There's no deployment of finished builds yet.

Added building debian packages as part of testing

---

.travis/build_deb.sh
.travis/build_rip_helper.sh
.travis/docker_run.sh
.travis/mk_runtests/run_tests.sh

- Set package version and release to meet [requirements][1] 1b and 1d in #791
- New environment variables to enable debug output in Travis CI logs
[1]: https://github.com/machinekit/machinekit/issues/791#issuecomment-158891001

Travis CI:  package versions; debug output

---

src/hal/cython/machinekit/hal_const.pxd
src/hal/lib/hal.h
src/hal/lib/hal_group.h

The code generated by Cython failed to build with newer versions of gcc, caused
by function passing wrong enum type:
Compiling hal/cython/machinekit/hal.c
hal/cython/machinekit/hal.c:1177:59: error: unknown type name ‘comp_type’
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_type(comp_type value);
To fix the issue, this patch creates typedef for all enums in HAL, and refer to
the proper type in hal_const.pxd. It just normalize the code, because other
enums were already using a typedef, except comp_type, compt_state and
report_phase.
Fixes https://github.com/machinekit/machinekit/issues/781
Signed-off-by: Francis Giraldeau <francis.giraldeau@gmail.com>

Fix Cython build because of enum type

---

.travis/docker_run.sh
.travis/mk_runtests/Dockerfile
.travis/mk_runtests/run_tests.sh
.travis/mk_runtests/run_tests_helper.sh

The contents of the log is then dumped whenever the runtests fails.

Enable rsyslog during regression testing.

---

.travis.yml
.travis/build_deb.sh
.travis/build_rip.sh
.travis/docker_run.sh

This is @kinsamanka's Travis CI Packagecloud integration.
If the Travis CI repo settings contain the `PACKAGECLOUD_USER`, `PACKAGECLOUD_REPO` and (private) `PACKAGECLOUD_TOKEN` variables, then Travis CI will upload packages to the packagecloud.io repository after a merge to master and successful package build.
The parent commit is a no-op variable cleanup commit.

Travis CI Packagecloud integration

---

.travis.yml
.travis/build_deb.sh
.travis/docker_run.sh
.travis/get_sftp_key.sh
.travis/send_binaries.sh
.travis/send_status.sh
.travis/upload_packagecloud.sh

This patch needs the following Travis-CI environment variables in order to work properly:
- `SFTP_DEPLOY_ADDR`
- `SFTP_DEPLOY_PORT` (default: **22**)
- `SFTP_DEPLOY_USER` (default: **travis**)
- `encrypted_sftp_key`
- `encrypted_sftp_iv`

Support for sftp deployment

---

src/hal/i_components/lgantry.icomp

Fix for a dangerous bug that can occur when homing is started at high
joint position. prev_cmd was initialized with 0 and therefore a resulted
in big position delta when switching to homing mode.

hal/components/lgantry: bug fix

---

.travis.yml
.travis/docker_run.sh
.travis/upload_packagecloud.sh

This PR introduces Travis CI builds for Jessie.  This completes the final flow for updating the deb.dovetail-automata.com package repo; see #791.
I have updated the Travis CI `machinekit/machinekit` settings to point to an updated set of Docker containers built from [my modifications][1] to @kinsamanka's repo; the most notable change is addition of Jessie containers.  [Docker Registry link][2]
The other changes in this commit are minor:
- Only push to packagecloud.io when building from the `master` branch (safety measure)
- Always run regression tests in the `run_tests` matrix (duh on my part)
[1]: https://github.com/zultron/mkdocker
[2]: https://hub.docker.com/r/zultron/mkdocker/builds/

Travis CI:  Jessie builds + minor updates

---

.travis.yml
.travis/docker_run.sh

This helps speed up the checks and reduces the load on travis-ci.

Only allow x64 builds for PR's

---

src/rtapi/Submakefile

fixes #677 on Ubuntu (at least 14.04)

rtapi/build: link rtapi_app_* with -Wl,--no-as-needed

---

src/Makefile

this fixxes the cython bindings on Ubuntu 14.04 and other platforms
which default to as-needed behavior
(repaired previous accidential direct push by undoing the last commit and posting this PR)

build: apply --no-as-needed to all binaries

---

src/hal/components/lcd.c
src/hal/drivers/hal_pru_generic/hal_pru_generic.c
src/hal/drivers/hal_zed_can.c
src/hal/drivers/mesa-hostmot2/bspi.c
src/hal/drivers/mesa-hostmot2/pins.c
src/hal/drivers/mesa-hostmot2/uart.c
src/machinetalk/msgcomponents/ringload.c

this should remove a couple of warnings
I wonder why this is suddenly criticial - is it the switch to gcc 4.9?

hal: fix up sprintf -> rtapi_snprintf usage

---

scripts/linuxcnc.in

The PRINT_FILE and DEBUG_FILE are generated by mktemp. Add symbolic links for them to /tmp/linuxcnc.print and /tmp/linuxcnc.debug to access current running status.
Also, the other process may access the INI file of current running Machinekit through /tmp/linuxcnc.print.
For example:
```python
inifile = None
lprint = open("/tmp/linuxcnc.print", "r")
for line in lprint:
m = re.match("^INIFILE=(.*)", line)
if (m):
inifile = m.group(1)
if (inifile):
ini = linuxcnc.ini(inifile)
else:
print "No valid INI_FILE_NAME, please launch Machinekit"
exit(1)
```

Make symbolic links for PRINT_FILE and DEBUG_FILE

---

.travis.yml
.travis/build_deb.sh
.travis/build_rip.sh
.travis/build_rip_helper.sh
.travis/docker_run.sh
.travis/get_ccache.sh
.travis/save_ccache.sh

Delete the travis env `DOCKER_CONTAINER` and then restart the tests. 
- gcc 4.7 for wheezy builds
- ccache support 
[travis-ci results](https://travis-ci.org/kinsamanka/machinekit/builds/97648560)
The Docker container was renamed due to issues encountered with the Docker registry autobuilder. Improvements made by @zultron on the original mkdocker container were incorporated into this new container. The dockerfiles can be found [here](http://github.com/kinsamanka/machinekit_builder)

Travis-CI Improvements

---

src/hal/i_components/offsetn.icomp
src/hal/utils/instcomp.g

Man page edit, clarifies that not all possible parameters and args
may be in use by all components
offsetn - multi-pin version of offset allowing 1-9 sets of pins
All pin sets are individual, allowing unique offsets per n axes
to be applied within same component
Fixes #870

Edit to instcomp man page generation and add new offsetn component

---

src/machinetalk/mkwrapper/mkwrapper.py

machinetalk/mkwrapper: fixing typo

---

.travis.yml

No available Xenomai kernel on RPi2

removed xenomai on raspbian

---

src/hal/utils/comp.g
src/hal/utils/instcomp.g

Whilst reworking instcomp in another branch, realised that the single
letter commandline switch for --install-document and --view-document
was set to the same at 'j'
Blame goes way back!
https://github.com/LinuxCNC/linuxcnc/commit/86e2aa61f89517057ffe6ac991103c7eb4739c1e

Minor edit to instcomp and comp

---

src/hal/drivers/mesa-hostmot2/hm2_soc.c
src/hal/drivers/mesa-hostmot2/hm2_soc.h

if u-boot does not load the fpga, and userland did not either, the FPGA
status is:
cat /sys/class/fpga/fpga0/status
power up phase
In this state, calling mmap(/dev/uio0) will currently crash the kernel
(at least 3.10.37-ltsi).
if the FPGA is loaded, either by u-boot or userland, status changes to
'user mode', and it is safe to mmap(/dev/uio0).
NB: 'user mode' persists a reboot - one needs to power off to return to
'power up phase' - something I overlooked
This patch guards against accidential mmap() if in 'power up phase', by
more prudently investigating the status, and recording if firmware= was
specified at the loadrt hm2_soc command line or not.
altera_fpga_status() takes some code from the Altera FPGA kernel module.
we can now drop boot-time loading of the FPGA firmware for good, …

hm2_soc: make robust against FPGA-not-loaded condition

---

configs/hm2-soc-stepper/5i25-soc-ol.ini
configs/hm2-soc-stepper/hm2-soc-ol-stepper-5i25.hal
src/Makefile
src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c
src/hal/drivers/mesa-hostmot2/hm2_soc_ol.h
src/hal/drivers/mesa-hostmot2/hostmot2-lowlevel.h
src/hal/drivers/mesa-hostmot2/hostmot2.c

Issue #903: This is the overlay based fpga driver used to get the Zynq port functioning correctly. 
I separated the driver into it's own module to keep backwards compatibility with the kernel 3 version altera soc code. This overlay based driver is generic - it should work on any fpga device provided it supports the configfs overlay based fpga framework.
The driver must be passed the name of the overlay file through the hostmot2 config string. Due to the way the bit file is passed to the low level drivers (i.e., too late), a new value had to be added to the low level io struct. Should not break any compatibility with other llio drivers. This avoids duplicating config string parsing in the low level driver.

#903 Adding overlay based hostmot2 fpga driver required by Zynq SoCs

---

src/hal/drivers/mesa-hostmot2/pktuart.c

* a typo prevented resetting the registers
A closing if-bracket came too late.
See also https://forum.linuxcnc.org/forum/24-hal-components/30262-reading-uart-rx-count-register-on-mesa-5i25-6i25?start=20#74416

Corrected: resetting the registers

---

debian/extras/usr/share/applications/linuxcnc-latency.desktop
debian/extras/usr/share/applications/linuxcnc-pncconf.desktop
debian/extras/usr/share/applications/linuxcnc-stepconf.desktop
debian/machinekit.install
debian/machinekit.postinst
debian/rules.in

Until full rebranding is done, ensure /usr/share/machinekit exists by
postinst symlink to /usr/share/linuxcnc
Reverted removal of 3 desktop links and updated
Fixes  #938 and fixes #939

Fix up of package paths and return 3 desktops

---

configs/hm2-soc-stepper/5i25-soc-cramps.ini
configs/hm2-soc-stepper/hm2-soc-stepper-5i25-cramps.hal
src/hal/drivers/mesa-hostmot2/hostmot2.h

Moved the hm2-soc-stepper-cramps config here from the mksocfpga repo.
Modest increase of hostmot2 firmware path length from 30 to 62 as per @dkhughes sugestion here:
https://github.com/machinekit/mksocfpga/issues/9#issuecomment-217850033

Hm2 soc cramps + firmware path length expansion

---

src/hal/utils/comp.g
src/hal/utils/instcomp.g

this caused the checksum compare during build to fail for every file
even if the content had not changed, causing longer build times

comp.g, instcomp.g: remove "generated" timestamps

---

src/emc/tp/blendmath.c

This fixes the following error ([tested on Ubuntu 16.04](https://www.youtube.com/watch?v=DMAiPX3bi8A)):
```
$ linuxcnc
MACHINEKIT - 0.1
Machine configuration directory is '/opt/machinekit.koppi/configs/sim/axis'
Machine configuration file is 'axis_mm.ini'
Starting Machinekit...
io started
halcmd loadusr io started
core_sim.hal:7: insmod failed, returned -1:
do_load_cmd: dlopen: /opt/machinekit.koppi/rtlib/posix/tp.so: undefined symbol: negate
rpath=/opt/machinekit.koppi/rtlib/posix:/opt/machinekit.koppi/lib
See /var/log/linuxcnc.log for more information.
Shutting down and cleaning up Machinekit...
Cleanup done
Machinekit terminated with an error.  You can find more information in the log:
/home/koppi/linuxcnc_debug.txt
and
/home/koppi/linuxcnc_print.txt
as well as in the output of the …
```

Remove 'inline' from negate function.

---

src/machinetalk/webtalk/webtalk.hh
src/machinetalk/webtalk/webtalk_defaultpolicy.cc
src/machinetalk/webtalk/webtalk_initproto.cc
src/machinetalk/webtalk/webtalk_main.cc
src/machinetalk/webtalk/webtalk_wsproxy.cc

see section 'v1.6.0-chrome48-firefox42' in
https://github.com/warmcat/libwebsockets/blob/v2.0-stable/changelog
this should support both the stretch (1.7.3) version and master (2.x)
not actually tested.
lws_get_internal_extensions() is deprecated and still needs work.
Should address #937 .

webtalk: support libwebsockets >= 1.6

---

configs/common/newthread.hal
configs/sim/axis/axis_mm.ini
configs/sim/axis/newthread.hal
src/emc/motion/command.c
src/emc/motion/control.c
src/emc/motion/mot_priv.h
src/emc/motion/motion.c
src/emc/motion/motion.h
src/rtapi/rtapi_pci.h

[hm, I force pushed and that didnt make it to the PR. Strange]
this has been a long-standing issue and became urgent because of #687 nearing conclusion - @dkhughesalso needs this
Since this is touching on critical parts of motion execution, let's merge this only after some more extensive testing - the runtests alone do not cut it
please use axis_mm.ini for testing as a model.
Thanks!
the iounmap() patch is a gcc 5 drive-by change, harmless I hope

Motion: make thread creation optional (take 2)

---

src/hal/utils/comp.g
src/hal/utils/instcomp.g

and exit.
When comp or icomp files are read in, the `\n` line endings are used
to split the file.
If `\r\n` DOS style or `\r` Mac style endings are present, it plays
havoc and a non specific failure results.
'Borrowed with pride' from jepler musings on same in
Emc-developers Digest, Vol 123, Issue 5

Provide specific warning of Mac and DOS line endings comp/instcomp

---

src/hal/utils/comp.g
src/hal/utils/instcomp.g

Fix 2 typos and missed rebranding in usage title in hal/utils/comp.g

---

debian/machinekit.install
debian/rules.in

The files and thus the path to the modules was changed but not duplicated
in the packaging
Had to specifically create the required directory in rules.in before
dh_install would work as intended, not sure why, but this debian config works
Fixes Issue #986

Fix package build to include lib/python/machinetalk/protobuf

---

src/hal/utils/comp.g
src/hal/utils/instcomp.g

Use predefined yaml variable `description:` to prevent parsing error

Amend (inst)comp manual page front-matter

---

src/machinetalk/mkwrapper/mkwrapper.py

load_tool_table caused the tool table to shift all indexes by one,
the first index in the tool table is irrelevant for most tool changers
anyway

mkwrapper: fix problem with load_tool_table

---

bin/mank

Pipe all output through `more` to eliminate problems with large files.
Add -h help switch additional to existing print on error
Add local dir path to preset search paths

Improve mank, asciidoc manual file terminal viewer script.

---

src/machinetalk/videoserver/video.ini
src/machinetalk/videoserver/videoserver.py

Allows custom arguments for mjpeg streamer (e.g. to enable http streaming).

videoserver: add custom arguments

---

bin/mank

Cater for RIP build but using installed package for manual pages.

Expand mank script find path spec for RIP build display

---

man/man1/machinekit.1

Should help anyone who only builds RIPs and does not
read websites, to figure out where the manual pages are.

Place a copy of the machinekit.1 stub in man/man1

---

share/axis/tcl/axis.tcl
src/emc/usr_intf/axis/scripts/axis.py

On amd64 the active axis selection 'current_axis' sometimes is set to an incorrect value, possibly by tk(inter).
Work around this by force-setting the variable in the radio button callback.
```
Traceback (most recent call last):
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
return self.func(*args)
File "/home/mb/develop/git/machinekit/bin/axis", line 2465, in touch_off
offset_axis = "xyzabcuvw".index(vars.current_axis.get())
ValueError: substring not found
```

axis: Workaround active axis selection issues on amd64

---

src/hal/drivers/mesa-hostmot2/pins.c

This allows hostmot2 firmwares to register themselves with custom pin counts instead of being forced into a traditional DB style connector size.

Allow hostmot2 to register non standard pin count connectors

---

src/hal/classicladder/serial_linux.c

This fixes the following compiler warning:
```
hal/classicladder/serial_linux.c: In function ‘SerialReceive’:
hal/classicladder/serial_linux.c:237:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if ( ModbusDebugLevel>=2 )
^~
hal/classicladder/serial_linux.c:239:4: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
NbrCarsReceived = read(fd,Buff,MaxBuffLength);
^~~~~~~~~~~~~~~
```

classicladder/serial_linux: Fix code ident

---

configs/hm2-soc-stepper/irqtest.hal
src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c

shaves off 10-20% off time spent in hm2_read/hm2_write
beating optimized library functions is usually not a good idea

hm2_soc_ol.c: speed up hm2_soc_read/hm2_soc_write

---

configs/sim/axis/xhc-hb04/xhc-hb04.tcl
src/hal/utils/halcmd_commands.c

This workaround is a temporary measure to keep the xhc-hb04 pendant working.
xhc-hb04.tcl uses commandline halcmd outputs against tests which are fixed
in expectation of a particular return. (ie from linuxcnc circa 2014)
Changes to halcmd print routines broke xhc-hb04.
This will tell the tcl code if a pin exists, removing the need for the
previous convoluted parsing of the stdout output.

Provide workaround to keep xhc-hb04 pendants working

---

src/hal/lib/hal_priv.h

The extra warnings now generated by gcc4.9 and higher, mean that hal_priv.h produces multiple warnings of 
`hal_priv.h :514    warning: type qualifiers ignored on function return type ...`
This is because hal_priv.h:514 has a declared `const int` return type and actually returns `int` , which is what `hal_funct_args_t->argc` actually is.

Amend hal_priv.h to remove compiler warnings

---

lib/python/machinekit/launcher.py

This function makes life a lot easier for Machinekit beginners.
add to a `run.py` script:
``` python
launcher.ensure_mklauncher()
```
and don't need to worry about mklauncher beeing laucnhed.

machinekit/launcher: adding ensure_launcher function

---

debian/machinekit-dev.install.in
debian/machinekit-posix.install
debian/machinekit-posix.install.in
debian/machinekit-rt-preempt.install
debian/machinekit-rt-preempt.install.in
debian/machinekit-xenomai.install
debian/machinekit-xenomai.install.in
debian/rules.in

Relates to Issue #1060
This PR will test whether Makefile.inc generated within
a build for xenomai flavour, will fix problem with comp
installing to the wrong flavour directory

Changes to debian packaging to add comp to main package

---

bin/mank

Switch mank to use the same default pager as man.

mank: Update pager

---

src/hal/utils/comp.g

The comp command fails to find include files for userspace comp files
and fails to initialize __comp_inst for singleton components that do
not use the FOR_ALL_INSTS() macro.
Fixes machinekit/machinekit#1067

comp: Fixes for compiling userspace components

---

src/hal/drivers/cpuinfo.c
src/hal/drivers/hal_gpio.c

/proc/cpuinfo returns
Hardware        : BCM2709
Revision        : a22082
I am unable to compile and test this patch at the moment due to configuration challenges.

Update hal_gpio driver for Raspberry Pi 3

---

src/machinetalk/mkwrapper/mkwrapper.py

This patch adds deleting tool table functionality to mkwrapper:
So far Machinetalk did not implement array item deletion behavior.
Deleting items of arrays works as follows:
- When the new array size is smaller than the old one new elements for the incremental are created.
- These new elements only contain the array index.
- The client then uses this information to delete values from the local array representation.

mkwrapper: implemented deleting of tool table entries

---

src/configure.ac
src/po/Submakefile
src/rebrand

Here are a few fixes from my tree.
The `configure.ac` commit actually fixes an issue, #1064.
The other two commits hide some build output.

Misc fixes:  fix #1064; cosmetic tweaks

---

debian/.gitignore
debian/configure
debian/control.in
debian/machinekit.install.in
src/Makefile
src/configure.ac
tests/module-loading/shared-test.sh

These are a last few tweaks needed for cross-building (or maybe "arising out of the cross-building effort").
- Remove package build-deps needed for building kernel threads
- This could be avoided, but it's easier than installing them into build container images, and aren't kthreads obsolete?
- Remove a FIFO left behind by one group of regression tests that isn't removed by `git clean` but that chokes `dpkg-source`
- Also not strictly needed for cross-building, but makes testing cross-building packages and RIP+tests from the same tree much easier

Final cross-build tweaks

---

src/Makefile

If building a RIP, does not account for module_loader not being present
in non kthread builds

Alter Makefile to prevent warning from `stat`

---

src/configure.ac

Changes in 0b36e4c did not work as anticipated and HAVE_GTK
was not defined, resulting in halmeter, halscope, classicladder
and all gtk dependent binaries not being built
Fixes #1083

Amend configure.ac HAVE_GTK test to use square bracketed args.

---

src/hal/drivers/cpuinfo.c

http://elinux.org/RPi_HardwareHistory

Add alternate rpi3 B board revision number for Rev4

---

src/hal/i_components/thc.icomp
src/hal/i_components/thcud.icomp
src/hal/icomp-example/instcomp.asciidoc
src/hal/utils/halcmd_commands.c
src/hal/utils/instcomp.g

The option was originally supported for backward compatibility,
however it really contradicts the basic concept of instantiation.
If a component cannot ever have more than one instance, it should
be written as a standard .comp
Arose initially from Issue #1094 where checking for other instances
of a component marked as a singleton, without proper mutex lock
was causing problems
On reflection the whole concept within instcomps was removed.
Whilst editing instcomp, corrected an error that had crept in during
changes to document generation, whereby the pin names were displayed
in the docs in C style rather than the HAL names
Fixes #1094
Corrects documentation issue in #1093

Deprecate `option singleton` in instantiated components

---

src/hal/components/thc.comp
src/hal/components/thcud.comp
src/hal/utils/comp.g

Further to #1095, as author is adamant component
should be a singleton and circumstances in which 2 plasma torches
might be used are unlikely, revert the .icomp versions back to .comp
where singleton is supported
Changes to comp.g to match those in instcomp.g in #1095, to
ensure that asciidoc man pages have component pin names with
HAL `-` separators not C `_` separators

Reinstate thc and thcud as standard components

---

src/machinetalk/mkwrapper/mkwrapper.py

adds a new flag to ensure that the tool table is really loaded after
executing the load_tool_table command

mkwrapper: ensure tool table loading

---

src/machinetalk/Submakefile

cp: cannot create regular file '../lib/python/machinetalk/protobuf/nanopb_generator.py': No such file or directory
machinetalk/Submakefile:277: recipe for target '../lib/python/machinetalk/protobuf/nanopb_generator.py' failed
make: *** [../lib/python/machinetalk/protobuf/nanopb_generator.py] Error 1

Fixes compilation issue with make -j8 - missing destination directory

---

src/emc/usr_intf/axis/extensions/emcmodule.cc

emc/usr_intf/axis/extensions/emcmodule.cc:298:42: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'Py_ssize_t' (aka 'long') in initializer list [-Wc++11-narrowing]
{(char*)"echo_serial_number", T_INT, O(echo_serial_number), READONLY},

Fixes the c++11-narrowing errors.

---

src/machinetalk/mkwrapper/mkwrapper.py

* fixes sync of status and command when `load_tool_table` is called
* considers `[EMCIO]RANDOM_TOOL_CHANGER` when updating tool entries

mkwrapper: tool table sync update

---

src/emc/usr_intf/stepconf/stepconf.py

Had the effect of introducing non-existent paths which prevented stepconf
from functioning properly
Fixes #1106 (hopefully)

Partially revert some re-branding from d319568

---

configs/hm2-soc-stepper/5i25-socfpga.ini

This results in newinst trying to load an instance called `hm2-socfpg0`
in the sample config.
This fails because the name must match that in the .dts files,
which is `hm2-socfpga0`

Remove typo which had perpetuated from initial commit of hm2_soc_ol instcomp

---

src/hal/drivers/hal_gpio.c

Corrects GPIO 5 which is on Pin#29 (not #20).

Fix pin assignment on Raspberry Pi 2/3

---

src/machinetalk/mkwrapper/mkwrapper.py

Will fix the regression with tooltable based "current tool in spindle" detection from QML GUI.

Fix RANDOM_TOOLCHANGER keyword spelling

---

src/machinetalk/mkwrapper/mkwrapper.py
src/po/zh_CN.po
src/po/zh_TW.po

1. mkwrapper.py: update_error(), convert text from str to unicode type
2. Update zh_CN.po and zh_TW.po for Chinese translations

mkwrapper.py: support unicode text messages for update_error()

---

src/rtapi/rtapi_math/e_asin.c
src/rtapi/rtapi_math/k_rem_pio2.c

Debian Stretch uses gcc-6.3.1 which has much stricter checking.
e_asin.c looks like C code written by a python programmer, it seems
to rely upon indentation to group operations, but in fact ends up with
only the first operation acted upon in the else option.
gcc-6.3.1 throws an error at this as previously noted in #1092
The www.scs.stanford.edu/histar/src/pkg/uclibc/libm/e_asin.c version of this
code where all indented operations are within else {} bracketing
appears to be the correct answer and code amended in that manner.
Uninitialised local double t, initialised to 0.0 instead of current 0
k_rem_pio2.c has 2 unbracketed operations after a for() loop on the same line.
This likewise was likely to be being rationalised so that only the first
operation was acted upon, which can't have been …

Fix rtapi_maths functions for use with gcc-6.3.1

---

lib/python/machinekit/launcher.py

`execfile` per default uses the namespace it is executed in which is not really what we want here.
I found this bug because it prevents functions using imports from working in Python HAL files.
For the records:
```
loading chip.py... Traceback (most recent call last):
File "./run.py", line 18, in <module>
launcher.load_hal_file('chip.py')
File "/home/alexander/bin/machinekit-1/lib/python/machinekit/launcher.py", line 121, in load_hal_file
execfile(filename)
File "chip.py", line 7, in <module>
test_func()
File "chip.py", line 5, in test_func
sig = hal.newsig('foo', hal.HAL_FLOAT)
NameError: global name 'hal' is not defined
```

machinekit/launcher: fix HAL file using wrong namespace

---

.travis/docker_run.sh

Set a default value for TRAVIS_PULL_REQUEST if it is not already
defined in the environment.  This makes it easier to do manual
cross-builds.

docker_run.sh: Add default value for TRAVIS_PULL_REQUEST

---

src/hal/drivers/hal_pru_generic/Submakefile

Explicitly set the file type to 'c' and set the output filename
using -o

hal_pru_generic: Fixup depend file generation

---

debian/machinekit.install.in
src/Makefile

Adds minor extra python methods
Fixes #1139

Include the nosetest subdir in machinekit package

---

scripts/realtime.in
src/libnml/cms/cms.cc
src/rtapi/ulapi_autoload.c

The term `INSTANCE` is too generic and causes conflicts with an default
environment variable on Ubuntu.
@zultron Can you please take a look at this PR.

scripts/realtime: replace INSTANCE term with MK_INSTANCE

---

debian/configure

KDE Neon is a Ubuntu (LTS) based distro featuring a current version of KDE and Qt. This patch adds the neon tag to the supported distros check.

debian/configure: add support for KDE Neon

---

src/Makefile

`hal_accessor_macros.h` is currently used undocumented by instcomp to define macros
used within the function code for atomic operation accessors.
Add to install, in preparation for rolling out info regards v2 components.
Will be in the main /include dir in a RIP, or in the machinekit-dev package.

Add accessor macros to install.

---

src/machinetalk/tutorial/rtapi-malloc-free/testalloc.comp

Whilst experimenting to try to find source of problem with memory leak
https://github.com/machinekit/machinekit/issues/1123#issuecomment-283065824
discovered that this component used old struct addressing to get size,
before it was made a union, requiring extra `.tag` inserted

Fix example testalloc.comp

---

src/machinetalk/proto/src/machinetalk/protobuf/types.proto

enums for s64 and u64 were missing and allocated to other fields
Fixes #1155

Fix type mismatch in Machinetalk Protobuf and hal.h

---

debian/machinekit.install.in
src/Makefile

The FDM configs will not work without deploying the Python libraries.

Makefile: fix ptyhon fdm/config deployment

---

lib/python/fdm/config/base.py

The formatting of `input` and `timeout` pins has changed. I also fixed the naming on the way.

lib/fdm: fix watchdog initialization

---

src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c
src/hal/lib/hal_lib.c
src/hal/utils/instcomp.g

In instantiated components created with instcomp,
make local_argv a char** to a locally allocated array of strings,
protecting against overwriting of the original args by subsequent calls,
in case required after instantiation.
Create a delete() function by default to explicitly free those strings.
This explicit free protects against the case where components are created
and deleted within a realtime system that continues to run,
thus reducing the heap memory available.
When realtime is stopped, the whole heap will be freed anyway.
Also fix stupid copy and paste typo in hm2_soc_ol, which would have
overwritten brd->config if anyone ever used the descriptor field.

Harden local copies of string variables in instantiated components.

---

src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c
src/hal/drivers/mesa-hostmot2/hm2_soc_ol.h
src/hal/lib/hal_lib.c
src/hal/lib/hal_memory.c
src/hal/lib/hal_priv.h

Explicit release of strdup'd memory upon closure of hm2_soc_ol
Remove const type from char pointers in brd struct that receive the
strdup pointers, to prevent compiler warnings
Add memory funcs to hal_memory.c / hal_priv.h and export
in hal_lib.c

More memory tidying

---

src/hal/i_components/charge_pump.icomp
src/hal/i_components/charge_pumpv2.icomp

Remove deprecated `singleton` option from charge_pump instcomps

---

src/machinetalk/haltalk/haltalk_command.cc
src/machinetalk/support/rtprintf.c

The first two fixes for a set of problems detected by the Coverity static analyzer. A lot more will follow.
See https://github.com/machinekit/machinekit/issues/391

Static analysis fixes

---

src/hal/utils/halcmd_main.c
src/rtapi/rtapi_compat.c

Potentially overunning fixed length buffers,
possible negative return used as param to calloc() etc.

Coverity error checking fixes

---

src/hal/i_components/time.icomp
src/hal/i_components/timev2.icomp

A complete line had been deleted from the function code,
with the effect that they did not update.
Upgraded to use fa_current_period() so that updates are more accurate.
Also catered for restart, which was never in original
by adding a zeroing pin.
Timings now can either be cumulative, with stops and starts
or reset to zero whilst timing or after a stop.

Fix time and timev2 instcomps

---

src/hal/utils/halcmd_main.c
src/rtapi/rtapi_compat.c

Was a unexpected knock on from 187f851 in fixing potential buffer
overruns etc detected by coverity scan
Also tidied halcmd_main buffer length to locally defined 200
(albeit this turned out not to be connected to the problem)

Fix error with flavor being unable to discern correct kernel

---

src/hal/components/delayline.c
src/hal/cython/machinekit/hal_component.pyx
src/hal/cython/machinekit/hal_pin.pyx
src/hal/cython/machinekit/hal_priv.pxd
src/hal/cython/machinekit/rtapi.pyx
src/hal/drivers/serport.comp
src/hal/lib/halmodule.cc
src/rtapi/rtapi_pci.c
src/rtapi/rtapi_pci.h

Repalces https://github.com/machinekit/machinekit/pull/1185
Another set of fixes for compiler warnings:
@ArcEye The inline keyword in the iounmap function is useless since GCC requires inline function to be defined and declared in the same translation unit. See https://gcc.gnu.org/gcc-5/porting_to.html
Please also take a close look at halmodule.cc

Compiler warning fixes2

---

src/hal/lib/hal_misc.c
src/hal/lib/hal_object.c
src/hal/lib/halpb.cc

Fix for https://github.com/machinekit/machinekit/issues/1187
Please review this patch carefully. I'm not 100 percent sure if looking for the *owner_id* is correct in all cases where `halpr_pin_count` and `halpr_describe_component` might be called.

Haltalk bind fix

---

src/machinetalk/haltalk/haltalk_command.cc
src/machinetalk/lib/pbutil.cc
src/rtapi/rtapi_app.cc

Arises from Issue #1197, where program is crashed , 
by a call to zframe_size(zframe_t *ptr) with a NULL pointer,
which triggers a failed assert()within zmq, which should never arise.

Fix use of untested zframe_t pointers in haltalk

---

src/emc/rs274ngc/previewmodule.cc
src/machinetalk/haltalk/haltalk_command.cc
src/machinetalk/haltalk/haltalk_group.cc
src/machinetalk/haltalk/haltalk_introspect.cc
src/machinetalk/haltalk/haltalk_rcomp.cc
src/machinetalk/include/pbutil.hh
src/machinetalk/lib/pbutil.cc

Reverts machinekit/machinekit#1201
Use throws undefined symbol error, suggesting that instances of the old syntax call remain in the code.
```ImportError: /usr/lib/python2.7/dist-packages/preview.x86_64-linux-gnu.so: undefined symbol: _Z16send_pbcontainerRKSsRN11machinetalk9ContainerEPv```

Revert "Deprecate send container string dest"

---

lib/python/gremlin_view.py
scripts/linuxcnc.in

Recently used above in project and found that it failed.
pgrep was failing to detect the inifile name from the running linuxcncsvr.
An errant sed operation had changed it to 'machinekitsvr', but even
when this was corrected, pgrep still errored thus
```
Traceback (most recent call last):
File "/usr/src/machinekit/bin/gremlin_view", line 3, in <module>
gremlin_view.standalone_gremlin_view()
File "/usr/src/machinekit/lib/python/gremlin_view.py", line 597, in standalone_gremlin_view
,yoffset=yoffset
File "/usr/src/machinekit/lib/python/gremlin_view.py", line 157, in __init__
if ini_setup():
File "/usr/src/machinekit/lib/python/gremlin_view.py", line 108, in ini_setup
ini_filename = get_linuxcnc_ini_file()
File "/usr/src/machinekit/lib/python/gremlin_view.py", line 135, in …
```

Fix current ini file detection by gremlin_view

---

configs/sim/axis/README
configs/sim/axis/axis_mm_drawbot.ini
configs/sim/axis/core_sim_drawbot.hal
src/Makefile
src/emc/kinematics/Submakefile
src/emc/kinematics/drawbotkins.c
src/emc/kinematics/kinematics.h

Add demo axis sim which allows loading and homing, needs work beyond that
Amend kinematics vtable struct to allow for `vtk_kinematicsHome_t`
which is used in drawbotkins, but unused eleswhere.
Added necessary vtable code to original drawbotkins.c to enable it to
function with updated machinekit kinematics code.

Add drawbotkins kinematic module

---

src/hal/jplanner/jplan.c

in queued mode this pin shows the output from the ringbuffer but
when using pins this needs to be in input otherwise we can't attach
a signal from elsewhere.

jplan.c: change pos-cmd pin IO to IN

---

lib/python/gremlin_view.py

Allows gremlin_view to be X embedded within another window after creation
as a standalone.
The switch -c | --childwindow prevents its top window being deiconified
at every poll, a mechanism which has the effect of raising the window
and keeping it on top.
This is very undesirable if embedding within a tab widget for example,
where switching tabs should render gremlin_view hidden

Add commandline switch to gremlin_view, to specify it is a child window.

---

src/hal/drivers/hal_pru_generic/hal_pru_generic.h
src/hal/drivers/hal_pru_generic/stepgen.c

This patch fixes the PRU DIR "pin hunting" problem by adding a minimum velocity pin.
This patch is sponsored by [Nectar 3D](http://nectar3d.com/).

hal_pru_generic: add minvel pin

---

lib/python/fdm/config/motion.py

Fixes problems with Delta-type printers and allows changing the motion pin counts for custom configurations.
Sponsored by [Nectar 3D](http://nectar3d.com/)

python/fdm: make motion loading more modular

---

src/hal/drivers/cpuinfo.c

Is a hardware revision correct for Pi 2 Model B v1.2 but is not recognised and returns rev 5, with fatal error resulting.
Fixes Issue #1223

Add hardware revision a22042 to comparisons

---

configs/ARM/BeagleBone/Fabrikator-Mini-CRAMPS/fabrikator-mini.ini
configs/ARM/BeagleBone/MendelMax-CRAMPS/CRAMPS.ini
lib/python/fdm/config/base.py

To make use of the new fix for PRU pin hunting we look for `STEPGEN_MIN_VEL` in the INI config. The PR makes the code easier to read and removes any errors potentially introduced by the additional PID loop and its parameters.
Thanks again to [Nectar3D](nectar3d.com) for the original patch for the PRU driver.

lib/fdm: use STEPGEN_MIN_VEL

---

.travis/upload_packagecloud.sh
debian/control.in
debian/machinekit-posix.install
debian/machinekit-posix.install.in
debian/machinekit-rt-preempt.install
debian/machinekit-rt-preempt.install.in
debian/machinekit-xenomai.install
debian/machinekit-xenomai.install.in
debian/rules.in

Out Of Tree builds have been broken for a long time on armhf packages.
Issue #1060 and others refer
The bottom of the problem is that the package machinekit-dev is built
with just posix flavour enabled, so as to avoid time constraints on
builds which otherwise would cause failure.
An unrealised consequence of this is that the file Makefile.inc,
which is pulled in by comp and instcomp, has flavours just set to
posix and the produced component targets posix, even if produced
on a rt-preempt or xenomai kernel.
machinekit-dev is largely an anachronism from linuxcnc days, when
in an effort to make the install as light as possible, all dev
stuff was in a seperate package.
This commit moves the -dev package files into the machinekit-\<flavour\>
package.  This ensures that the Makefile.inc …

Fix armhf builds so that required elements exist for comp OOT builds.

---

src/configure.ac

This var was introduced to allow for architecture specific switches
required for some arm boards.
However there was no AC_SUBST() macro exporting the var and recent tests
where I used the var to pass args for cross-building, showed that it was
not being substituted in Makefile.inc.in, so having no effect.
AC_SUBST(ARCH_CFLAGS) inserted and fixes.

Fix configure.ac build environment variable `ARCH_CFLAGS`

---

src/hal/cython/machinekit/hal_loadusr.pyx

If we don't wait for HAL components to become ready we may run into race conditions.

hal: fix race conditions with loadusr

---

debian/control.posix.in
debian/control.rt-preempt.in
debian/control.xenomai.in
debian/rules.in

Reverse testing commenting out of Makefile.inc Makefile.modinc and comp, to ensure files are deleted before creation of main machinekit package.
Add `Breaks: machinekit-dev` property to all machinekit-{flavour}
packages debian/control files, to prompt upgraders to remove that old package, which conflicts.

Fix  overflow into Machinekit package

---

src/emc/usr_intf/axis/scripts/axis.py

Pressing 'I' triggers an error because a tuple is used as an
argument to int()
Solution is simply to specify index of [0]
Can't see how this ever worked, maybe no-one used it.
Fixes #1239

Fix jog increment hot key in Axis

---

configs/ARM/BeagleBone/BeBoPr++/Pepper/ReadTemp.py
configs/ARM/BeagleBone/BeBoPr++/Pepper/setup.bridge.sh
configs/ARM/BeagleBone/BeBoPr++/Pololu/ReadTemp.py
configs/ARM/BeagleBone/BeBoPr++/Pololu/setup.bridge.sh
configs/ARM/BeagleBone/BeBoPr++/ReadTemp.py
configs/ARM/BeagleBone/BeBoPr++/setup.bridge.sh
configs/ARM/BeagleBone/BeBoPr-Bridge/ReadTemp.py
configs/ARM/BeagleBone/BeBoPr-Bridge/setup.bridge.sh
configs/ARM/BeagleBone/BeBoPr/ReadTemp.py
configs/ARM/BeagleBone/PocketNC/ReadTemp.py
configs/ARM/BeagleBone/Replicape/hal_temp_bbb

Daren Schwenke tested with 3.8.x and 4.4.x
https://groups.google.com/d/msg/machinekit/RrNLUo4ASP4/Ye6sNvyYBgAJ
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
CC: Daren Schwenke <darenschwenke@gmail.com>
CC: Charles Steinkuehler <charles@steinkuehler.net>

configs/ARM: BeagleBone: use generic iio sysfs path for adc

---

debian/configure

Currently package version is set by Travis writing a debian/changelog entry 
setting the version from vars inside Travis prepended onto the existing changelog.  
If building manually or via a different CI system, this patch gives the option of calling 
'debian/configure -c <other-args>', which will create a changelog entry with a version derived from information within git and the running system.  
The version will be derived from 
`<machinekit main version>.<number of commits>-1.git<SHA>~<distro>`
Option also included 'debian/configure -s <other-args>' to create sources. 
.orig tarball created with a version format which will allow creation of .debian tarball and .dsc file, 
when doing package build from command line or otherwise outside Travis environment  
Has no effect upon existing …

Options in debian/configure, set package version and create sources. 

---

debian/configure
debian/control.rt-preempt-stretch.in

The control-rt-preempt.in file specifies a particular rt-preempt kernel
in the deb.machinekit.io repo
This was because Jessie dropped rt-preempt support creating unmet
dependencies.
Stretch now supports rt-preempt, so debian/configure specifies a generic
`linux-image-rt [amd64|i386]` dependency, which Debian can meet.
Also simplify further the parsing routines to generate package serial

Have debian/configure differentiate Stretch builds

---

debian/configure
debian/control-stretch.in
debian/extras/etc/ld.so.conf.d/czmq-zeromq.conf
debian/machinekit.install.in

Two depended packages have substantially changed their numbering
ie. python-gst0.1 becomes python-gst-1.0
gstreamer0.1-plugins-base becomes gstreamer1.0-plugins-base
python-zmq depends upon later versions of zmq (libzmq5) so cannot be a dep.
Specify czmq and zeromq to bring in the libs built which use the
previous API.
Add an /etc/ld.so.conf.d/ entry to ensure it caches /usr/local/lib
configure detects distro codename and makes substitutions if
Stretch detected - so will not affect existing builds
Now tested with a from scratch install on amd64 and works

Dependency changes for Stretch packaging

---

debian/control.posix.in
debian/control.rt-preempt-stretch.in
debian/control.rt-preempt.in
debian/control.xenomai.in

Left out when comp etc. moved and machinekit-dev deprecated
Fixes #1246

Restore yapps dependency to machinekit-flavour packages.

---

configs/hm2-soc-stepper/5i25-soc-cramps.ini
configs/hm2-soc-stepper/hm2-soc-stepper-5i25-cramps.hal
src/Makefile
src/hal/drivers/mesa-hostmot2/capsense.c
src/hal/drivers/mesa-hostmot2/hostmot2.c
src/hal/drivers/mesa-hostmot2/hostmot2.h
src/hal/drivers/mesa-hostmot2/nano_soc_adc.c
src/hal/drivers/mesa-hostmot2/pins.c
src/hal/user_comps/Submakefile
src/hal/user_comps/hal_temp_atlas.py

This commit adds (tested to work):
hostmot2 support for socfpga ADC (tested on DE0_Nano_SoC) (same ADC as on DE10-Nano)
A hal_temp_atlas user component for 3d-print temperature conversion derived from hal_temp_bbb.
(with an optional reference voltage input on adc ch 8)
Support for a simple high precision capasitive touch sensor that can be used for
tool probing or a contact-less limit switch, etc.
Kicad schematic and board-layout here:
https://github.com/the-snowwhite/socfpga-kicad/tree/work/Touch-sense2
The complementary fpga project is the original DE0_Nano_Soc_GHRD project morphed and reduced to be only fully CRAMPS compatible atm currently residing here:
https://github.com/the-snowwhite/mksocfpga/tree/DE0_Nano_SoC_Cramps
(I expect to get the last workaroun for the capsense core in …

De0 nano soc cramps

---

src/configure.ac

Add specific arch flag (-m=32|-m=64) for platform_pc builds
Ensures proper linkage upon multi-arch system
or within a multi-arch docker container.
These flags already exist in Machinekit-HAL and have zero impact on
a single arch system, as they just repeat what the linker would expect.

Add ARCH_CFLAGS for platform_pc builds

---

debian/rules.in

If machinekit packages are built upon a multi-arch enabled Debian system,
dh_python2 renames the python libraries to {libname}.{arch}.so
As machinekit libraries are not intended to be multiarch, just one arch
and flavour installed at a time, this is both unnecessary and breaks
packages because the default library name is not able to be found.

Fix dh_python2 multi-arch renames of libraries.

---

scripts/build_docker
scripts/build_packagecloud_upload
scripts/build_source_package

Will have no effect on current builds in Travis, which use others.
Once Wheezy support is dropped, these will be required for faster
builds of Jessie through a Jenkins job as per Machinekit-HAL.

Add the cross-builder specific scripts for future use.

---

debian/armhf.postrm.in
debian/configure
debian/control.posix-stretch.in
debian/control.xenomai-stretch.in
debian/machinekit-rt-preempt.install.in
debian/posix-postinst.add
debian/pru-postinst.in
debian/rt-preempt-postinst.add
debian/rules.in
debian/xenomai-postinst.add
scripts/build_docker
scripts/build_source_package
src/Makefile
src/configure.ac
src/hal/components/hal_pru.c
src/hal/drivers/hal_pru_generic/Submakefile

They will now be located at $EMC2_RTLIB_BASE_DIR/prubin for binaries
and $EMC_HOME/rtlib/prubin for RIP builds
ie. in a dir immediately alongside the existing flavour dirs
then symlinked to each flavour dir so that existing configs are unchanged.
This largely mirrors the commits to Machinekit-HAL.
Fixes the underlying problem in #1199, #1182 and #1238 
Should now allow the use of later 4.x rt-preempt kernels with BBB and other arm boards

Make PASM created pru_generic* binaries flavour independent.

---

src/machinetalk/mklauncher/mklauncher.py

A Very simple patch to fix the behavior of reading the stdout of processes when the output does not contain a newline character.
E.g.
```
(write)Loading blabla...(flush) done\n
```

mklauncher: read stdout in chunks and not in lines

---

src/machinetalk/mklauncher/mklauncher.py
src/machinetalk/mklauncher/test_mklauncher.py

It turns out configparser causes trouble with dots in the section name.

mklauncher: use absolute path for importances

---

scripts/build_docker

The `mk-cross-builder` scripts are being updated for Stretch, and tags
will append `_9` to signify Stretch.

scripts/build_docker:  updates for Stretch

---

src/machinetalk/support/unionread.c

Compiling machinetalk/support/unionread.c
machinetalk/support/unionread.c: In function ‘print_container’:
machinetalk/support/unionread.c:60:33: warning: \
format ‘%lu’ expects argument of type ‘long unsigned int’, \
but argument 2 has type ‘uint64_t {aka long long unsigned int}’ \
[-Wformat=]
printf("submessage length=%lu\n", length);
^

machinetalk/support/unionread.c:  silence compile warning

---

src/machinetalk/mkwrapper/mkwrapper.py

Previously clients have not been notified about all tool table entries when a new entry has been added. This patch fixes the problem.

mkwrapper: fix incremental update of tool table when modified

---

debian/posix-postinst.add
debian/rt-preempt-postinst.add
debian/xenomai-postinst.add

Prevents any warnings etc. when an updated package is installed
on top of an existing package which also made the symlinks.

Force creation of symlinks for armhf pru_*.* binaries

---

src/configure.ac

Logic changed so that --enable-webtalk or --enable-webtalk=yes
will enable webtalk build
--enable-webtalk=no or --disable-webtalk or no switch at all,
will disable the build of webtalk
Fixes issue @
https://github.com/machinekit/machinekit/issues/1152#issuecomment-336050599

configure.ac allowed an argument of --disable-webtalk to activate it.

---

src/hal/cython/machinekit/rtapi.pyx

Fix for https://github.com/machinekit/machinekit/issues/1294

cython/rtapi: fix identity comparison

---

src/hal/drivers/hal_bb_gpio/hal_bb_gpio.c

Fix for problem introduced by: https://github.com/machinekit/machinekit/commit/41a5deff2ab9463ae53213aa3d3195f6b34d7a27#diff-33d49c1dd2784aad48ad40ab6a13069c
invert pins should be input pins as they invert the pin signal

hal_bb_gpio: fix invert pin direction

---

src/hal/lib/hal_thread.c
src/rtapi/rtapi_task.c

This addresses #1306. The original #941 changes seem to be adding in the missing multicore pieces to the mainline, and these are the only required modifications after the multicore merge.

Allow RT threads to specify nowait

---

src/Makefile

see also:
https://github.com/machinekit/Machinekit-HAL/pull/27/commits/369d82ac6b86aece36ef2b86d78de54b29948c3b
jplan and interpolator were not properly linked

Makefile: machinetalk protobuf jplan and interpolator linking

---

debian/configure
debian/control.stretch.in
src/emc/usr_intf/gmoccapy/gmoccapy.py
src/emc/usr_intf/gscreen/gscreen.py

Debian have removed the python module `gst` from the python-gst-1.0 package available for Stretch.
This breaks gmoccapy GUI and means no sounds in gscreen.
The python-gst-1.0 package was backported by Debian to Jessie, which then created the same errors in Jessie packages too.
This reverts Jessie packages to `python-gst0.10` which does have `gst` module, removes python-gst deps from Stretch packages and adds distro based conditional tests to gmoccapy and gscreen, as to whether they should create an audio player, which is dependent upon module `gst` being available.
Fixes Issue at https://github.com/machinekit/machinekit/issues/1228#issuecomment-345339637
until author does more permanent revision

Remove python-gst deps for Stretch package builds

---

nc_files/remap_lib/python-stdglue/stdglue.py

The functionality to return `INTERP_EXECUTE_FINISH` in a python remap
function has always existed, but was broken until PR
linuxcnc/linuxcnc#135.
The fix revealed a bug in the standard remap `change_epilog()`
function, which was not written as a python generator function.
Thanks to @dhwiezel for discovering and reporting this bug.  Fixes
linuxcnc/linuxcnc#217.
Signed-off-by: John Morris john@zultron.com

stdglue.py:  turn `change_epilog()` into generator function

---

debian/configure
debian/control.buster.in
debian/rules.in
scripts/build_docker
scripts/build_source_package
src/configure.ac

Remove dependency on python-gtksourceview2 deprecated in Buster
Amend packaging to support Buster package builds
arceye/mk-cross-builder:amd64|armhf|i386 needs specifically selecting
but otherwise build process is identical and no custom packages reqd.
Remove defunct kernel threads options in rules.in and configure.ac 

 Add support for Debian Buster package builds 

---

src/emc/usr_intf/emclcd.cc

Appears not worth the effort of converting this to use `ip a` and `ip route` to replace `ifconfig` and `netstat` respectively.
The output is different and would require a re-write of something it is unlikely anyone uses.
The package net-tools is still available, so test for netstat and ifconfig
and warn users that they need to install that package if not found.

Add note to emclcd.cc re Stretch onwards

---

src/hal/drivers/mesa-hostmot2/hm2_soc_ol.c
src/hal/drivers/mesa-hostmot2/hm2_soc_ol.h

this patch is allowing to use HM2 based soc boards pre-programmed fpga, good example is terrasic de10nano
successfully tested under fedora arm 27 + kernel 4.14.3 + rt5 + u-boot preloaded fpga on DE10-NANO
hal driver initialisation example:
newinst [HOSTMOT2](DRIVER) [HOSTMOT2]DEVNAME already_programmed=1 -- config=[HOSTMOT2](CONFIG)

add support for soc boards with pre-programmed fpga

---

tests/linuxcncrsh/skip
tests/mdi-queue/oword-queue-buster/skip
tests/mdi-queue/simple-queue-buster/skip
tests/t0/nonrandom/skip
tests/t0/random-with-t0/skip
tests/t0/random-without-t0/skip
tests/toolchanger/toolno-pocket-differ/nonrandom/skip
tests/toolchanger/toolno-pocket-differ/random/skip

Quite a few runtests rely upon linuxcncrsh used in conjunction with
`tcping` or `nc`
The netcat package containing these binaries has been deprecated,
starting at Stretch, along with a lot of the old net-utils.
(Even ifconfig is not available unless specifically installed,
from the package net-tools)
Add a `skip` script to those tests which require deprecated binaries
to test for presence and skip if not found.
Not doing so will cause the failure of that and every subsequent
test because the linuxcnc/halcmd processes are left running.

Fix runtests for Stretch and Buster

---

src/hal/drivers/hal_gpio_demo.hal

This changed back to being a requirement with the multicore merge.  
Will default to no floating point.

Set slow (servo) thread to floating point

---

src/hal/i_components/dummy_stepgen.icomp

Adds a dummy_stepgen component for simulators.
This component just loops back the position commands. It's intended to be used as drop-in replacement for a stepgen component in simulator configs.

hal/i_components: add dummy_stepgen

---

src/libnml/posemath/_posemath.c

This is based on inspection of rcslib-2014.04.29 but is not a direct
copy as the API was changed from taking pointers to taking copies
when it comes to inputs that are not changed.
One of the atan2 calls is also changed.
Author: Jepler@unpythonic.net
Closes #1350

posemath: Adapt upstream changes - import from linuxcnc #5724d8f59.

---

src/hal/drivers/hal_gpio_h3.c

Full support of **H3 SoC** port/pin names for the **hal_gpio_h3** driver.
The driver is backward compatible with current hal config files.
**Example**:
- **PA15** - red SMD led on the OPi1 board
- **PL10** - green SMD led on the OPi1 board
- **PL3**  - push button on the OPi1 board
```
loadrt hal_gpio_h3 output_pins=PA15,PA12,PA11,PA6,PA13,11,13,36,38,PL10 input_pins=PL3
net estop-out       => hal_gpio_h3.pin-PA15-out
net xstep           => hal_gpio_h3.pin-PA12-out
net xdir            => hal_gpio_h3.pin-PA11-out
net ystep           => hal_gpio_h3.pin-PA6-out
net ydir            => hal_gpio_h3.pin-PA13-out
net zstep           => hal_gpio_h3.pin-11-out
net zdir            => hal_gpio_h3.pin-13-out
net spindle-cw      => hal_gpio_h3.pin-36-out
net spindle-pwm     => hal_gpio_h3.pin-38-out …
```

Orange Pi H3 port/pin names support for the GPIO driver

---

src/hal/drivers/cpuinfo.c

Add BCM2835 hardware to recognised processor types for RPi3

---

scripts/realtime.in
src/hal/lib/hal_object_selectors.h
src/hal/utils/halcmd_commands.c
src/rtapi/rtapi_app.cc
tests/rtapi.0/test.sh

Here's a stack of patches resulting from trying to run a comp both built *and installed* out-of-tree.
This fixes an issue loading comps from a given path instead of a given filename within the rpath.
There are also a couple of trivial fixes for module handling-related things I noticed along the excursion, a patch to `realtime.in` with various minor fixes, and a fix for the `rtapi.0` test that breaks on Ubuntu (prob. due to differences in the Ubuntu linker build-time options, previously discussed).

Module loading and debugging

---

src/Makefile.modinc.in

Out-of-tree build system needs a way of adding CFLAGS to RT compile
commands, such as Sascha Ittner's EtherCAT RT comp, which must include
the EtherLab header files.

Makefile.modinc:  add EXTRA_RTFLAGS to EXTRA_CFLAGS

---

src/rtapi/rt-preempt.c
src/rtapi/rt-preempt.h
src/rtapi/rtapi.h
src/rtapi/rtapi_common.c
src/rtapi/rtapi_common.h
src/rtapi/rtapi_task.c
src/rtapi/ulapi_autoload.c
tests/pll_correction/checkresult
tests/pll_correction/pll_correction.comp
tests/pll_correction/pll_correction.hal
tests/pll_correction/pll_time.h
tests/pll_correction/test.sh

Any objections to adding @sittner's [PLL correction patch][1] to Machinekit?
This patch helps with EtherCAT distributed clock (DC) synchronization problems.  Previously, the `lcec` comp forced EtherCAT slaves to synch with the master clock running on Linux.  The problem was that if the Linux OS realtime latency wasn't sufficiently jitter-free, the slaves would fault with a DC synch error.
One solution to this is to synch the master DC with a slave clock.  See [linuxcnc-ethercat issue #45][2] for more discussion.  This patch provides a way to adjust the RTAPI period to put the master into a PLL with the slave DC so that the two clocks don't drift away from each other over time.
[1]: https://github.com/sittner/linuxcnc-ethercat/blob/c84a868b/patches/add-task-pll-functions.patch
[2]: …

Port sittner's add-task-pll-functions.patch to Machinekit

---

tests/pll_correction/README.md
tests/pll_correction/checkresult
tests/pll_correction/params.py.sh
tests/pll_correction/pll_correction.comp
tests/pll_correction/pll_correction.hal
tests/pll_correction/test.sh

A MK [Jenkins build for an unrelated PR][1] failed in this test,
meaning that this test's parameters are too restrictive, even for
non-RT POSIX threads.
This commit:
- Fixes an integer overflow that caused it to fail on
systems with very high jitter
- Desensitizes the test by only requiring the test be within 1% of the
total phase offset
Other changes:
- Add README.md
- Parameterize PERIOD & NUMSAMPS
[1]: https://jenkins.machinekit.io/job/machinekit-PR-builder/68/console

tests/pll_correction:  fix integer overflow error; desensitize

---

src/hal/cython/machinekit/rtapi.pyx

Commit 080f48d7 failed to address this case, calling `loadrt` from the
python rtapi module.
See PR #1367.

Fixup 080f48d7, "Fix out-of-tree module loading"

---

src/machinetalk/mkwrapper/mkwrapper.py

FTP was not working after the last update. Turns out `pyftplib` does not support new-style classes.

mkwrapper: fix new style class problems

---

src/Makefile
src/hal/drivers/mesa-hostmot2/setsserial.c
src/rtapi/userpci/Submakefile

this patch returns setsserial module (a utility for setting Smart Serial NVRAM parameters)
tested it today with de10nano (hm2_soc_ol) + 7i76 in setup mode
Jun 16 11:43:08 de10cnc rtapi:0[14537]: 4:rtapi_app:14537:user setsserial.so default iparms: ''
Jun 16 11:43:08 de10cnc rtapi:0[14537]: 4:rtapi_app:14537:user halg_xinitfv:90 HAL: initializing component 'setsserial' type=1 arg1=0 arg2=0/0x0
Jun 16 11:43:08 de10cnc rtapi:0[14537]: 1:rtapi_app:14537:user Firmware Flash Success
Jun 16 11:43:08 de10cnc rtapi:0[14537]: 4:rtapi_app:14537:user setsserial: loaded from setsserial.so
test script (for hm2_soc_ol):
loadrt hostmot2 sserial_baudrate=115200 debug_idrom=1 debug_module_descriptors=1 debug_pin_descriptors=1 debug_modules=1
newinst hm2_soc_ol hm2-socfpga0 already_programmed=1 -- config="" …

return back hm2 setsserial module

---

src/rtapi/rt-preempt.c

@luminize reports this fills up logs when `DEBUG=5`.

rt-preempt.c:  disable pll correction debug messages

---

src/hal/i_components/limit3.icomp
src/hal/i_components/limit3v2.icomp

The limit3 HAL component could be brought in a state where the output slowly keeps creeping into one direction. This was a result of `old_v` never updating with adequate values in some cases where limiting was active before halting the input.

Fix limit3 creeping

---

scripts/realtime.in

These three changes all relate to shutting down realtime:
- Fix a problem where zombie processes are falsely detected as running `rtapi_app` instances
- This is common running in Docker, where no proper `init` process reaps zombies
- Stop faster and smarter:
- Replace the `sleep 2.5` with a loop to detect exit faster than that
- As above, fix exit detection when zombies are not reaped
- Allow `msgd` 5 seconds instead of 2.5 to exit gracefully
- Some complex HAL comps may need extra time to shut down

`scripts/realtime stop` updates

---

src/hal/i_components/lincurve.icomp

Arose during multicore merge when an older version was committed
reversing an earlier fix.
Fixes #1390

Revert inadvertent change to lincurve.icomp.

---

configs/ARM/BeagleBone/Rostock-4DOF-CRAMPS/README.md
configs/ARM/BeagleBone/Rostock-4DOF-CRAMPS/rostock-3dof.py
configs/ARM/BeagleBone/Rostock-4DOF-CRAMPS/run.py

While i was working on docs and requested changes - code was merged
so created new pull request
this pull request will sync rostock-3dof.py file with configs/ARM/BeagleBone/MendelMax-CRAMPS/mendelmax.py as was described in comment: https://github.com/machinekit/machinekit/pull/1385#discussion_r206775377
Put more details in Readme
and switch default setup to 3DOF configuration (usual LinearDelta style) - as it will be more usable for community

Sample config - changing from 4DOF as default to 3DOF

---

debian/control.stretch.in

Revert removal from stretch, which was in limbo at the time.

python-gst-1.0 now backported throughout active distros replacing 0.10

---

configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.bbio
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.ini
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.ini
configs/ARM/BeagleBone/BeBoPr-Bridge/setup.bridge.sh
configs/ARM/BeagleBone/CRAMPS/CRAMPS.ini
configs/ARM/BeagleBone/Xylotex/Xylotex.ini

Fixed configs for BeBoPr-Bridge to run on Stretch.
Changed ini files to have consistent "PROGRAM_PREFIX"
not sure yet which is best, but my inclination is "PROGRAM_PREFIX = ~/machinekit/nc_files".
https://github.com/machinekit/machinekit/commit/2d8a5da5bee062a1c0953ef23c2f2c993a0f20f
https://github.com/machinekit/machinekit/commit/c6bf459c80958b55ef44e1348457078e9c19b80d0

Changes to Configs to run on Stretch

---

src/rtapi/Submakefile

Used only in RIP builds, until all flavour related paths are removed, these symlinks are created from postinst file in packages

Improve rtapi/Submakefile creation of symlinks to module flavours

---

debian/posix-postinst-arm.add
debian/rt-preempt-postinst-arm.add
debian/xenomai-postinst-arm.add
src/Makefile

In moving flavour symlink creation inside a conditional test, left package arm postinst installs without the base flavour dir to link to.

Fix symlink flavour dir creation disrupted by 45b4c7d

---

configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.bbio
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.ini
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.ini
configs/ARM/BeagleBone/BeBoPr-Bridge/setup.bridge.sh
configs/ARM/BeagleBone/CRAMPS/CRAMPS.bbio
configs/ARM/BeagleBone/CRAMPS/CRAMPS.hal
configs/ARM/BeagleBone/CRAMPS/CRAMPS.ini
configs/ARM/BeagleBone/CRAMPS/setup.sh
configs/ARM/BeagleBone/Xylotex/Xylotex.bbio
configs/ARM/BeagleBone/Xylotex/Xylotex.hal
configs/ARM/BeagleBone/Xylotex/Xylotex.ini
configs/ARM/BeagleBone/Xylotex/setup.sh
debian/configure
debian/control.buster.in
debian/control.sid.in
debian/control.stretch.in
src/Makefile
src/emc/kinematics/itripodkins.c
src/hal/user_icomps/Submakefile

The flavour changes had resulted in the current flavour not being set properly for rtapi_main
which caused a fatal error.
Unfortunately this was not picked up, because the unset variable equates to `0` which is the enum for `posix`, so if you test it on a posix build (as I did) it all works fine.
I don't have time to fix right now, so this PR is a hard reset back to before the commits which caused problems with the non-controversial commits cherry-picked back in.
This works on a rt-preempt kernel and all flavour package builds work locally, so hopefully will provide breathing space until I have time to revisit

Revert flavour changes

---

debian/configure
debian/control.sid.in
debian/control.stretch.in

Situation at 20092018
python-gst1.0 backported to Jessie + Stretch
This affects gmoccapy, which uses functions in the old lib, but checks were introduced in
https://github.com/machinekit/machinekit/commit/5e5bb64 to remove those if newer distro used.
These remain valid as python-gst-0.10 is not available for Stretch and above even though the
newer lib is available in Jessie.
python-gtksourceview2 is still not available for Buster, but Sid has it, so expect backport soon
This is used in gladevcp widgets.
python-pil and python-pil.imagegtk active for Sid replacing python-imaging and python-imaging-tk
however selecting python-imaging and python-imaging-tk in Stretch actually
results in python-pil and python-pil.imagegtk being installed, so will probably completely backport soon.
Keep …

Update debian/control.xxx.in files

---

src/hal/drivers/hal_spi.c
src/hal/drivers/hal_spi.h

Driver was written when only Rpi 1 & 2 existed
RPi 3B has a different base address from which everything
thereafter is offset from
Test version and set base address.

Change hal_spi driver to test for Rpi version

---

src/hal/components/encoder_ratiov2.c
src/hal/components/encoderv2.c
src/hal/components/pwmgenv2.c
src/hal/components/rtfault.comp
src/hal/components/stepgenv2.c
src/hal/cython/machinekit/hal_component.pyx
src/hal/cython/machinekit/hal_util.pxd
src/hal/i_components/Submakefile
src/hal/icomp-example/icomp.c
src/hal/icomp-example/lutn-demo.c
src/hal/lib/hal.h
src/hal/lib/hal_comp.c
src/hal/lib/hal_funct.c
src/hal/lib/hal_internal.h
src/hal/lib/hal_memory.c
src/hal/lib/hal_object_selectors.c
src/hal/lib/hal_priv.h
src/hal/lib/hal_rcomp.c
src/hal/lib/hal_rcomp.h
src/hal/user_icomps/watch.c
src/hal/userfunct-example/ufdemo.c
src/hal/utils/instcomp.g
src/machinetalk/haltalk/haltalk_rcomp.cc

This silences the compiler warnings related to `const` not addressed in PR #1410.
See machinekit/machinekit-cnc#45

Mk pr compiler warnings 2018 10 10

---

src/hal/utils/halcmd_commands.c

Made this change in machinekit-hal repo as part of the compiler silencing
commits, but omitted from machinekit.
The print line is executed anyway at the end of the switch() block

Remove double printed line in event of no match L:1978 halcmd_commands.c

---

lib/python/machinekit/launcher.py

Sometimes process keep sticking around as zombies. However, we can ignore them when we are checking for processes.

machinekit/launcher: make sure zombies are excluded from running process

---

src/hal/drivers/hal_pru_generic/encoder.c
src/hal/drivers/hal_pru_generic/hal_pru_generic.h

I made this change to my local RIP build about 2 years ago and forgot to share it, so my memory is a little hazy.
I have been using it on my lathe for both threading and rigid tapping with a 1024 P/Rev quadrature spindle encoder and it works well for me.

Add missing index handling to the pru encoder

---

scripts/build_docker

The gcc 8.x used in Buster and above throws many warnings not covered in the
commits to remove them from Jessie and Stretch.

Restrict CFLAG -Werror to Jessie and Stretch builds

---

.travis/check_sftp.sh
.travis/send_binaries.sh
.travis/send_status.sh
debian/configure
debian/linuxcnc-sim.sharedmimeinfo
scripts/build_docker
src/Makefile
tests/pll_correction/skip

This PR contains several patches related to the CI system and package builds.
As discussed in machinekit/machinekit-hal#150 and Dovetail-Automata/mk-cross-builder#3, the Emdebian project is defunct, and it became impossible to rebuild the Docker images to support `armhf` builds for Jessie.  @dkhughes provided the initial example I used to replace the Emdebian's cross-compile toolchain with Linaro's, and mk-cross-builder again builds images that are at least able to build the Jessie ARM packages (running them has not been tested).  A couple of patches here are related to that, and the RT `CPPFLAGS` patch is required to complete Xenomai builds (the commit log will inadequately elucidate why).
Other patches tidy up, fix unofficial Travis CI instances, disable the unreliable `pll_correction` …

CI system updates

---

src/hal/user_comps/mb2hal/mb2hal.c

Courtesy of Dale Lukas Peterson <hazelnusse@gmail.com> and linuxcnc commit
https://github.com/LinuxCNC/linuxcnc/pull/106/commits/5bdebef86dce6b56ecbb122f6dde29f85afbef0f
Debian sid now includes libmodbus 3.1.4-1 which breaks existing API
Can be expected to filter down through the backports
Fixes machinekit-hal/issues/166

Add libmodbus version checks

---

src/machinetalk/videoserver/videoserver.py

Videoserver currently fails to launch mjpg-streamer:
user.log:Dec 10 06:26:12 hevo MJPG-streamer [2303]:        dlopen:  /usr/local/lib/mjpg-streamer/output_zmqserver.so --address tcp://*:59241 --buffer_size 1: cannot open shared object file: No such file or directory

Add missing backslash to escape quote

---

src/hal/user_comps/huanyang-vfd/hy_vfd.c

1. changed retval/looptime/errorcount from hal_param to hal_pin
1. these signals were not accessible to other components such as pyvcp as described in the documentation
1. fixed scaling of ACV/DCV pins
1. the scaling was *10, thus scaled down to /10 to be in [A], [V] instead of 10[A], 10[V]
1. renamed CLI argument for voltage from -V to -U to also comply with -I for current
1. since on CLI the current [A] argument is denoted as -I, -V for [V] is confusing and thus should be -I

minor hy_vfd fixes (scaling, cli args, hal param vs. pin)

---

src/hal/user_comps/xhc-whb04b-6/hal.cc
src/hal/user_comps/xhc-whb04b-6/hal.h
src/hal/user_comps/xhc-whb04b-6/main.cc
src/hal/user_comps/xhc-whb04b-6/pendant.cc
src/hal/user_comps/xhc-whb04b-6/pendant.h
src/hal/user_comps/xhc-whb04b-6/xhc-whb04b6.cc
src/hal/user_comps/xhc-whb04b-6/xhc-whb04b6.h

Wen updating component's documentation a few minor things popped up and were fixed on the fly: 
1. refined `--help` output
1. fixed compiler warning when const method `foo() const {...}` called non-const `foo(){...}` implementation
1. fixed issue with log output where log was not silent upon cli request `-n`
1. added missing rotary button output signals to component
1. added `whb.halui.spindle.start` signal upon user request
1. minor cleanup

xhc-whb04b-6 component: code cleanup

---

scripts/build_docker

Ensure that the Docker image isn't stale by running `docker pull`.
Just now, even though the CI images on Docker hub are refreshed (see machinekit/machinekit-hal#163), the Jenkins run on PR #1426 failed because that PR depends on some cgroups-related packages that aren't in the old CI images.  This PR fixes that kind of issue.

scripts/build_docker:  run `docker pull`

---

scripts/linuxcnc.in

Here's a little patch that could save someone else time someday when `linuxcnc` exits ungracefully.
-----
When things are really broken, `$HALCMD list comp` may output nothing,
yielding the error:
/usr/bin/linuxcnc: line 582: [: =: unary operator expected

Fix linuxcnc script bug

---

src/hal/utils/halcmd_commands.c
src/rtapi/rtapi_app.cc
src/rtapi/rtapi_support.c

The big problem was when `DEBUG=1`, errors weren't being logged; for
example, in `sampler.c`, the "SAMPLER: ERROR: depth too large" message
wasn't printed, and the only information in the logs was the
mysterious "rtapi_app_main(sampler): -12 Cannot allocate memory".
This patch also reverts a line commented out in 2694a4b1, causes
`rtapi_print()` to always print, and fixes `set_msg_level()` for
ULAPI.

Fix logging problems

---

src/Makefile
src/hal/user_comps/xhc-whb04b-6/Submakefile
src/rtapi/rtapi.h
src/rtapi/rtapi_global.h
src/rtapi/rtapi_io.h

Warnings in C++ sources aren't halting build when
`DPKG_CFLAGS=-Werror` set.  See mk-cnc issue 45.
https://github.com/machinekit/machinekit-cnc/issues/45

Silence compiler warnings

---

src/hal/cython/machinekit/hal_loadusr.pyx

When passing `command` as a list with `shell=True`, the safer form of
the call, fix the error message string build for a non-zero return
code.

Fix python error message for `loadusr(shell=True)`

---

scripts/build_docker

Enables use of normal docker for machinekit-manpages production
The current Jenkins manpages job uses a docker within a proot shell, which has proved problematic.
This will enable the same system as other dockers, with the UID/GID set in a custom container at runtime.

Add docs build option directly to build_docker script

---

src/Makefile
src/hal/sample_channel/sample_channel.hal
src/hal/sample_channel/sample_channel_pb.c
src/hal/sample_channel/show_hal_sample.py
src/machinetalk/msgcomponents/Submakefile
src/machinetalk/msgcomponents/pbmsgs.c
src/machinetalk/msgcomponents/pbmsgs.h
src/machinetalk/proto/src/machinetalk/protobuf/sample.proto

This PR introduces an instantiatiable component called "sample channel" which samples HAL pins, encodes them in a protobuf "Sample" message and puts those values in a HAL ring.
The userland side can connect to the HAL ring, get the records, and decode the Sample message. Example python script shows how.

src/hal/sample_channel: add sample_channel component

---

src/hal/drivers/hal_pru_generic/hal_pru_generic.c

Changed calls to rtapi_print to call rtapi_print_msg with a lower priority RTAPI_MSG_DBG.
This should allow the information to be available for debugging without showing up everytime you start the program.

Replace rtapi_print( with rtapi_print_msg(RTAPI_MSG_DBG,

---

src/hal/drivers/hal_pru_generic/pwmgen.c

Another occurrence of rtapi_print affected by “logging fix” which changed rtapi_print’s use of RTAPI_MSG_ERR to RTAPI_MSG_ALL. Hopefully the last.

Another occurrence of rtapi_print affected by “logging fix”

---

configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.bbio
configs/ARM/BeagleBone/CRAMPS/CRAMPS.bbio
configs/ARM/BeagleBone/Xylotex/Xylotex.hal
configs/ARM/BeagleBone/Xylotex/Xylotex.ini

Fixed setup.sh for CRAMPS — needs to be executable.
Both CRAMPS and BeBoPr-Bridge were missing .bbio files.

Fixed some missed changes in Xylotex.ini, Xylotex.hal and setup.sh.

---

configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.bbio
configs/ARM/BeagleBone/BeBoPr-Bridge/BeBoPr-Bridge.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/lineardelta.hal
configs/ARM/BeagleBone/BeBoPr-Bridge/setup.sh

Pin assignments in BeBoPr-Bridge.hal and lineardelta.hal were for BBB with BeBoPr rather that BBB with BeBoPr+Bridge. Hopefully someone with hardware that actually runs on the BeBoPr+Bridge can test it. All I can test is that machine kit starts and runs on a BeBoPr+Bridge without attached hardware.

Fix BeBoPr-Bridge pin assignments

---

scripts/build_docker
src/machinetalk/support/unionread.c
src/rtapi/rtapi_pci.c

Commits attempt to remove warnings arising from data types having
different sizes under 32 and 64 bit.
However assigning void pointers instead of `long long uint`
and casting to `void *` where reqd , to avoid a warning, 
resulted in non functioning rtapi_pci, preventing hm2_pci from working.
scripts/build_docker CFLAGS addition of -Werror removed for now.
Fixes https://groups.google.com/forum/#!topic/machinekit/KQFyNEsnblE

Revert e207745 and b55b544 and remove -Werror CFLAG

---

src/machinetalk/haltalk/Submakefile
src/rtapi/Submakefile

Prevent DSO errors in later versions of gcc
Cherry-picked from machinekit-hal, this prevents errors when building on sid

Add specific -lzmq to CFLAGS to prevent DSO errors in later distros.

---

scripts/build_docker
src/machinetalk/support/unionread.c
src/rtapi/rtapi_pci.c

Fixes a problem introduced in commit e207745f.  Thanks to Dennis for
reporting the problem and locating the problematic commit on the [ML][1].
[1]:  https://groups.google.com/d/msg/machinekit/KQFyNEsnblE/gX_-g36tCQAJ
Also submitted as machinekit/machinekit-hal#188

rtapi/rtapi_pci.c: Fix PCI resource file parsing

---

src/rtapi/rtapi_support.c

This reverts part of commit 77a23d3 from PR #1452.
The `rtapi_print()` function was set to never print, and that PR
changed it to always print, as the comments in `rtapi.h` indicate it
should.  However, the result was that it spews messages out the error
channel, which show up in Axis.  That's bad.
This reverts back to the "never print" behavior until a better
solution comes along.

rtapi_support.c:  Temp. silence `rtapi_print()`

---

src/hal/utils/Submakefile

This commit removed the linkage against libtclstub.a because it produced warnings
of possible unused symbols.
machinekit/machinekit@d1fed9c#diff-b95f3ce6cb4f8632848c66ea2be6b1f5
Reverting machinekit, so that it has the same linkage in tcl/hal.so
that machinekit-hal does, removes the 'undefined reference to tclStubPtr' error.

Linkage of tcl/hal.so against libtclstub.a is necessary for tcl

---

src/emc/usr_intf/axis/extensions/emcmodule.cc
src/machinetalk/mkwrapper/mkwrapper.py

This little change allows remote interfaces to ask the active interpreter to synchronize state on demand.

Expose interp synch command through python/machinetalk

---

src/hal/utils/Submakefile

signed off by mick (arceye@mgware.co.uk)

Backport #456555d from mk-hal to accomodate Fedora builds

---

src/rtapi/Submakefile

This to prevent a reported DSO error when building on Raspian
whereby __atomic_fetch() etc used by rtapi functions are
not resolved by newer linkers
Also moved -lrt and -lzmq there for uniformity.

Add libatomic to RTAPI_MSGD_LDFLAGS - bugfix
